# Generated by Django 5.2.8 on 2026-01-13 06:28
# Migration pour renommer les modèles Partner → Contact (classes Python uniquement)
# Les tables BDD restent inchangées grâce à db_table

from django.db import migrations


class Migration(migrations.Migration):
    """
    Renomme les modèles Python Partner → Contact.
    Les tables en BDD restent nommées partners_* (via db_table).
    Des alias sont conservés pour la rétrocompatibilité.
    """

    dependencies = [
        ('partners', '0001_create_partners_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='PartnerRole',
            new_name='ContactRole',
        ),
        migrations.RenameModel(
            old_name='PartnerTag',
            new_name='ContactTag',
        ),
        migrations.RenameModel(
            old_name='PartnerTagLink',
            new_name='ContactTagLink',
        ),
        migrations.RenameModel(
            old_name='PartnerEvent',
            new_name='ContactEvent',
        ),
    ]
