# Generated by Django 5.2.8 on 2026-01-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_rename_models_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Rôles du partenaire (client, fournisseur, etc.)', related_name='contacts', to='partners.contactrole'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='partners.contact'),
        ),
        migrations.AlterField(
            model_name='contacttaglink',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='partners.contacttag'),
        ),
    ]
