# Generated by Django 5.0.14 on 2025-09-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_vendange_parcelle_to_ref'),
        ('referentiels', '0004_rename_referentiels_cepage_org_name_norm_idx_referentiel_organiz_49d2b6_idx'),
        ('viticulture', '0004_lotcontainer_lotdetail_lotdocument_lotintervention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottechnique',
            name='cuvee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_techniques', to='viticulture.cuvee'),
        ),
        migrations.AddField(
            model_name='lottechnique',
            name='external_lot_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Pont vers lot externe', null=True),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='cuvee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendanges', to='viticulture.cuvee'),
        ),
        migrations.AlterField(
            model_name='lottechnique',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('stabilise', 'Stabilisé'), ('pret_mise', 'Prêt mise'), ('conditionne_partiel', 'Conditionné partiel'), ('epuise', 'Épuisé')], default='en_cours', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lottechnique',
            index=models.Index(fields=['cuvee', 'statut', 'campagne'], name='production__cuvee_i_fcbe59_idx'),
        ),
        migrations.AddIndex(
            model_name='vendangereception',
            index=models.Index(fields=['cuvee', 'date'], name='production__cuvee_i_26c9ff_idx'),
        ),
    ]
