# Generated by Django 4.2.7 on 2025-10-02 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_create_default_orgsettings'),
        ('production', '0005_add_nom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('entity_type', models.CharField(choices=[('lottech', 'Lot technique'), ('mise', 'Mise (OF)'), ('tirage', 'Tirage / Lot commercial'), ('ms_stock', 'Stock matières sèches')], max_length=20)),
                ('entity_id', models.UUIDField(help_text="UUID de l'entité de référence")),
                ('nature', models.CharField(choices=[('vrac_in', 'Entrée vrac'), ('vrac_out', 'Sortie vrac'), ('vrac_loss', 'Perte vrac'), ('ms_in', 'Entrée MS'), ('ms_out', 'Consommation MS'), ('mo', "Main d'œuvre"), ('overhead', 'Frais généraux')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, help_text='Quantité (L ou unité MS)', max_digits=14)),
                ('amount_eur', models.DecimalField(decimal_places=4, help_text='Montant en EUR', max_digits=14)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Écriture de coût',
                'verbose_name_plural': 'Écritures de coûts',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('lottech', 'Lot technique'), ('mise', 'Mise (OF)'), ('tirage', 'Tirage / Lot commercial'), ('ms_stock', 'Stock matières sèches')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('cmp_vrac_eur_l', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cmp_pack_eur_u', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('mo_eur_u', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cout_unitaire_eur_u', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snapshot de coût',
                'verbose_name_plural': 'Snapshots de coûts',
            },
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='bennes_palox',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='contenant',
            field=models.CharField(blank=True, help_text="Contenant cible saisi à l'encuvage", max_length=64),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='etat_sanitaire',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='etat_sanitaire_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='prix_raisin_eur_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Prix d'achat raisin (EUR/kg)", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='rendement_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('receptionnee', 'Réceptionnée'), ('affectee_cuvee', 'Affectée à une cuvée'), ('encuvee', 'Encuvée/Pressurée'), ('close', 'Clôturée')], default='receptionnee', max_length=20),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='tri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='tri_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='type_recolte',
            field=models.CharField(choices=[('blanc', 'Blanc'), ('rouge', 'Rouge'), ('rose', 'Rosé'), ('base_effervescente', 'Base effervescente')], default='blanc', max_length=20),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='type_vendange',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('machine', 'Machine')], default='manuel', max_length=12),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='volume_mesure_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='vendangereception',
            index=models.Index(fields=['campagne'], name='production__campagn_4ae83f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendangereception',
            index=models.Index(fields=['organization'], name='production__organiz_6809c7_idx'),
        ),
        migrations.AddField(
            model_name='costsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='costentry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='costsnapshot',
            index=models.Index(fields=['entity_type', 'entity_id'], name='production__entity__ba6832_idx'),
        ),
        migrations.AddConstraint(
            model_name='costsnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'entity_type', 'entity_id'), name='unique_cost_snapshot_per_entity'),
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['organization', 'entity_type', 'entity_id', 'date'], name='production__organiz_396ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['organization', 'nature', 'date'], name='production__organiz_0b8428_idx'),
        ),
    ]
