# Generated by Django 4.2.7 on 2025-10-02 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0006_costentry_costsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ENTREE_INITIALE', 'Entrée initiale'), ('SOUTIRAGE', 'Soutirage'), ('ASSEMBLAGE_IN', 'Assemblage (entrée)'), ('ASSEMBLAGE_OUT', 'Assemblage (sortie)'), ('TRANSFERT_IN', 'Transfert (entrée)'), ('TRANSFERT_OUT', 'Transfert (sortie)'), ('PERTE', 'Perte'), ('MISE_OUT', 'Mise (sortie)')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='production.lottechnique')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['lot', 'date', 'type'], name='production__lot_id_7aae52_idx')],
            },
        ),
    ]
