# Generated by Cascade on 2025-10-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_mouvementlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendangereception',
            name='kg_debites_cumules',
            field=models.DecimalField(default=0, max_digits=12, decimal_places=2),
        ),
    ]
