# Generated by Django 4.2.7 on 2025-10-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('produits', '0006_alter_mise_state'),
        ('production', '0008_vendange_add_kg_debites_cumules'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(choices=[('bouteille', 'Bouteille'), ('bouchon', 'Bouchon'), ('capsule', 'Capsule'), ('etiquette', 'Étiquette'), ('carton', 'Carton'), ('autre', 'Autre')], max_length=30)),
                ('uom', models.CharField(default='u', max_length=20)),
                ('pack_qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('stock_min', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cmp_eur_u', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MSReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.msitem')),
                ('mise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.mise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MSMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price_eur', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('nature', models.CharField(choices=[('ms_in', 'Entrée (achat)'), ('transfer_in', 'Transfert +'), ('transfer_out', 'Transfert −'), ('ms_out', 'Consommation (mise)'), ('adjust_pos', 'Inventaire +'), ('adjust_neg', 'Inventaire −'), ('scrap_out', 'Rebut')], max_length=20)),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.msemplacement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.msitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.msemplacement')),
            ],
        ),
    ]
