# Generated by Django 4.2.7 on 2025-10-21 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_create_default_orgsettings'),
        ('production', '0009_msemplacement_msitem_msreservation_msmove'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(choices=[('cuve_inox', 'Cuve inox'), ('cuve_beton', 'Cuve béton'), ('cuve_fibre', 'Cuve fibre'), ('fut_225', 'Fût 225L'), ('foudre', 'Foudre'), ('amphore', 'Amphore'), ('autre', 'Autre')], default='cuve_inox', max_length=32)),
                ('capacite_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacite_utile_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('localisation', models.CharField(blank=True, max_length=120)),
                ('temperature_cible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thermo_regule', models.BooleanField(default=False)),
                ('date_dernier_nettoyage', models.DateField(blank=True, null=True)),
                ('cycle_nettoyage_j', models.IntegerField(blank=True, null=True)),
                ('date_dernier_ouillage', models.DateField(blank=True, null=True)),
                ('cycle_ouillage_j', models.IntegerField(blank=True, null=True)),
                ('note_sanitaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('nettoyage', 'En nettoyage'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
                ('volume_occupe_l', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenants', to='production.lottechnique')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['organization', 'code'], name='production__organiz_74e3c7_idx'), models.Index(fields=['organization', 'statut'], name='production__organiz_87fe56_idx')],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
