# Generated by Django 4.2.7 on 2025-11-15 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_dashboardwidget_widget_type'),
        ('production', '0010_contenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottechnique',
            name='analytics_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lottechnique',
            name='composition_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lottechnique',
            name='volume_v20_hl',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lottechnique',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('stabilise', 'Stabilisé'), ('pret_mise', 'Prêt mise'), ('conditionne_partiel', 'Conditionné partiel'), ('epuise', 'Épuisé'), ('MOUT_ENCUVE', 'Moût encuvé'), ('MOUT_PRESSE', 'Moût de presse'), ('MOUT_DEBOURBE', 'Moût débourbé'), ('VIN_EN_FA', 'Vin en FA'), ('VIN_POST_FA', 'Vin post-FA'), ('VIN_EN_FML', 'Vin en FML'), ('VIN_POST_FML', 'Vin post-FML'), ('VIN_ELEVAGE', 'Vin en élevage'), ('VIN_STABILISE', 'Vin stabilisé'), ('VIN_FILTRATION_STERILE', 'Vin filtré stérile'), ('VIN_PRET_MISE', 'Vin prêt mise'), ('BASE_EFF', 'Base effervescente'), ('SUR_LATTES', 'Sur lattes (tirage)'), ('DEGORGEMENT', 'Dégorgement/Dosage')], default='en_cours', max_length=32),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('encuvage', 'Encuvage'), ('pressurage', 'Pressurage/Décuvage'), ('assemblage', 'Assemblage'), ('fa', 'Fermentation alcoolique'), ('fml', 'Fermentation malolactique'), ('stabilisation', 'Stabilisation/Collage'), ('filtration_sterile', 'Filtration stérile'), ('tirage', 'Tirage (effervescents)'), ('degorgement', 'Dégorgement/Dosage'), ('mise', 'Mise'), ('vrac_charge', 'Chargement vrac'), ('transfert', 'Transfert interne'), ('analyse', 'Analyse'), ('autre', 'Autre')], max_length=32)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LotLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, help_text='Part du parent dans l’enfant (0..1)', max_digits=12, null=True)),
                ('child_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='production.lottechnique')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineages', to='production.operation')),
                ('parent_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_links', to='production.lottechnique')),
            ],
            options={
                'verbose_name': 'Filiation de lot',
                'verbose_name_plural': 'Filiations de lots',
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['organization', 'kind', 'date'], name='production__organiz_d3eed8_idx'),
        ),
        migrations.AddIndex(
            model_name='lotlineage',
            index=models.Index(fields=['operation'], name='production__operati_f20088_idx'),
        ),
        migrations.AddIndex(
            model_name='lotlineage',
            index=models.Index(fields=['parent_lot'], name='production__parent__11b9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lotlineage',
            index=models.Index(fields=['child_lot'], name='production__child_l_11c50f_idx'),
        ),
    ]
