# Generated by Django 4.2.7 on 2025-11-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_lottechnique_analytics_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottechnique',
            name='location_kind',
            field=models.CharField(choices=[('ONSITE', 'Sur site'), ('OFFSITE', 'Hors site'), ('IN_TRANSIT', 'En transit')], default='ONSITE', max_length=16),
        ),
        migrations.AddField(
            model_name='lottechnique',
            name='volume_hl20',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('encuvage', 'Encuvage'), ('pressurage', 'Pressurage/Décuvage'), ('assemblage', 'Assemblage'), ('fa', 'Fermentation alcoolique'), ('fml', 'Fermentation malolactique'), ('stabilisation', 'Stabilisation/Collage'), ('filtration_sterile', 'Filtration stérile'), ('tirage', 'Tirage (effervescents)'), ('degorgement', 'Dégorgement/Dosage'), ('mise', 'Mise'), ('vrac_charge', 'Chargement vrac'), ('transfert', 'Transfert interne'), ('offsite_send', 'Envoi hors site'), ('offsite_return_neutral', 'Retour hors site (neutre)'), ('offsite_return_non_neutral', 'Retour hors site (non neutre)'), ('analyse', 'Analyse'), ('autre', 'Autre')], max_length=32),
        ),
    ]
