# Generated by Django 5.2.8 on 2025-11-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_clear_cuvee_refs'),
        ('referentiels', '0007_importbatch_parcelle_cepages_importexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottechnique',
            name='cuvee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_techniques', to='referentiels.cuvee'),
        ),
        migrations.AlterField(
            model_name='vendangereception',
            name='cuvee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendanges', to='referentiels.cuvee'),
        ),
    ]
