# Generated by Django 5.2.8 on 2025-11-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_alter_lottechnique_cuvee_and_more'),
        ('referentiels', '0009_add_zones_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendangereception',
            name='cepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendanges', to='referentiels.cepage', verbose_name='Cépage'),
        ),
    ]
