# Generated by Django 5.2.8 on 2025-11-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_add_cepage_to_vendange'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendangereception',
            name='rang_debut',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang début'),
        ),
        migrations.AddField(
            model_name='vendangereception',
            name='rang_fin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang fin'),
        ),
    ]
