# Generated by Django 5.2.8 on 2025-11-30 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_add_vendange_rangs'),
        ('referentiels', '0009_add_zones_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendangereception',
            name='poids_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='VendangeLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité (kg)')),
                ('rang_debut', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang début')),
                ('rang_fin', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang fin')),
                ('rangs_texte', models.CharField(blank=True, help_text='Ex: 1-5, 10-12', max_length=100)),
                ('degre_potentiel', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('etat_sanitaire', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cepage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendange_lignes', to='referentiels.cepage')),
                ('vendange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='production.vendangereception')),
            ],
            options={
                'verbose_name': 'Ligne de vendange',
                'verbose_name_plural': 'Lignes de vendange',
                'ordering': ['cepage__nom'],
            },
        ),
    ]
