# Generated by Django 5.2.8 on 2025-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_add_vendange_lignes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenant',
            name='annee_mise_service',
            field=models.PositiveIntegerField(blank=True, help_text='Année de première utilisation', null=True),
        ),
        migrations.AddField(
            model_name='contenant',
            name='forme',
            field=models.CharField(blank=True, choices=[('cylindrique', 'Cylindrique'), ('tronconique', 'Tronconique'), ('ovoide', 'Ovoïde'), ('rectangulaire', 'Rectangulaire'), ('autre', 'Autre')], help_text='Forme de la cuve (optionnel)', max_length=32),
        ),
        migrations.AddField(
            model_name='contenant',
            name='grain_bois',
            field=models.CharField(blank=True, choices=[('extra_fin', 'Extra fin'), ('fin', 'Fin'), ('moyen', 'Moyen'), ('gros', 'Gros')], help_text='Grain du bois', max_length=32),
        ),
        migrations.AddField(
            model_name='contenant',
            name='origine_bois',
            field=models.CharField(blank=True, choices=[('francais', 'Français'), ('americain', 'Américain'), ('mixte', 'Mixte'), ('hongrois', 'Hongrois'), ('autre', 'Autre')], help_text='Origine du bois (barriques/foudres)', max_length=32),
        ),
        migrations.AddField(
            model_name='contenant',
            name='statut_barrique',
            field=models.CharField(blank=True, choices=[('neuve', 'Neuve'), ('1_vin', '1 vin'), ('2_vins', '2 vins'), ('3_vins_plus', '3 vins et +'), ('a_reformer', 'À réformer')], help_text="Statut d'usage de la barrique/foudre", max_length=20),
        ),
        migrations.AddField(
            model_name='contenant',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Température maximale conseillée (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contenant',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Température minimale conseillée (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contenant',
            name='tonnelier',
            field=models.CharField(blank=True, help_text='Nom du tonnelier / fabricant', max_length=100),
        ),
        migrations.AddField(
            model_name='contenant',
            name='type_chauffe',
            field=models.CharField(blank=True, choices=[('legere', 'Légère'), ('moyenne_moins', 'Moyenne -'), ('moyenne', 'Moyenne'), ('moyenne_plus', 'Moyenne +'), ('forte', 'Forte')], help_text='Type de chauffe', max_length=32),
        ),
        migrations.AddField(
            model_name='contenant',
            name='type_thermoregulation',
            field=models.CharField(blank=True, choices=[('double_enveloppe', 'Double enveloppe'), ('serpentin', 'Serpentin'), ('drapeaux', 'Drapeaux'), ('ceinture', 'Ceinture extérieure'), ('autre', 'Autre')], help_text='Type de système de thermorégulation', max_length=32),
        ),
        migrations.AlterField(
            model_name='contenant',
            name='temperature_cible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Température cible (legacy) - préférer min/max', max_digits=5, null=True),
        ),
    ]
