# Generated by Django 5.2.8 on 2025-12-08 17:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('production', '0018_contenant_extended_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'analyse")),
                ('type_analyse', models.CharField(choices=[('complete', 'Analyse complète'), ('so2', 'Contrôle SO₂'), ('pre_mise', 'Pré-mise'), ('microbiologique', 'Analyse microbiologique'), ('autre', 'Autre')], default='complete', max_length=20, verbose_name="Type d'analyse")),
                ('origine', models.CharField(choices=[('interne', 'Labo interne'), ('externe', 'Labo externe')], default='interne', max_length=10, verbose_name='Origine des résultats')),
                ('labo_externe_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du laboratoire externe')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('prelevement', 'Prélèvement effectué'), ('attente_resultats', 'En attente résultats'), ('resultats_saisis', 'Résultats saisis'), ('validee', 'Validée')], default='resultats_saisis', max_length=20, verbose_name='Statut')),
                ('densite', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.900')), django.core.validators.MaxValueValidator(Decimal('1.200'))], verbose_name='Densité à 20°C')),
                ('tav', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='TAV (% vol)')),
                ('sucres_residuels', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sucres résiduels (g/L)')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('2.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='pH')),
                ('acidite_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Acidité totale (g/L H₂SO₄)')),
                ('acidite_volatile', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Acidité volatile (g/L H₂SO₄)')),
                ('acide_malique', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Acide malique (g/L)')),
                ('acide_lactique', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Acide lactique (g/L)')),
                ('so2_libre', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SO₂ libre (mg/L)')),
                ('so2_total', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SO₂ total (mg/L)')),
                ('potentiel_redox', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Potentiel redox (mV)')),
                ('so2_commentaire', models.TextField(blank=True, verbose_name='Commentaire SO₂')),
                ('azote_assimilable', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Azote assimilable (mg/L)')),
                ('turbidite', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Turbidité (NTU)')),
                ('couleur_do420', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DO 420nm')),
                ('couleur_do520', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DO 520nm')),
                ('couleur_do620', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DO 620nm')),
                ('ipt', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='IPT (Indice Polyphénols)')),
                ('parametres_extra', models.JSONField(blank=True, default=dict, verbose_name='Paramètres supplémentaires')),
                ('note_globale', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note globale (1-5)')),
                ('notes_degustation', models.TextField(blank=True, verbose_name='Notes de dégustation')),
                ('commentaires_internes', models.TextField(blank=True, verbose_name='Commentaires internes')),
                ('alerte_declenchee', models.BooleanField(default=False, verbose_name='Alerte déclenchée manuellement')),
                ('alerte_type', models.CharField(blank=True, choices=[('so2_bas', 'SO₂ libre bas'), ('volatile_elevee', 'Acidité volatile élevée'), ('ph_eleve', 'pH élevé'), ('ph_bas', 'pH bas'), ('suspicion_microbio', 'Suspicion microbiologique'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'alerte")),
                ('alerte_description', models.TextField(blank=True, verbose_name="Description de l'alerte")),
                ('alerte_recommandation', models.CharField(blank=True, max_length=200, verbose_name='Recommandation de suivi')),
                ('prochaine_analyse_date', models.DateField(blank=True, null=True, verbose_name='Date prochaine analyse recommandée')),
                ('niveau_alerte', models.CharField(choices=[('ok', 'OK'), ('surveillance', 'À surveiller'), ('alerte', 'Alerte')], default='ok', max_length=15, verbose_name="Niveau d'alerte")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='production.lottechnique', verbose_name='Lot en élevage')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Analyse œnologique',
                'verbose_name_plural': 'Analyses œnologiques',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'date'], name='production__organiz_ded454_idx'), models.Index(fields=['lot', 'date'], name='production__lot_id_eca756_idx'), models.Index(fields=['niveau_alerte'], name='production__niveau__67bb03_idx'), models.Index(fields=['statut'], name='production__statut_331368_idx')],
            },
        ),
    ]
