# Generated by Django 5.2.8 on 2025-12-12 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0019_analyse_oenologique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alert_type', models.CharField(choices=[('draft', 'Brouillon à finaliser'), ('reminder', 'Rappel'), ('action', 'Action à effectuer'), ('threshold', 'Seuil dépassé'), ('deadline', 'Échéance'), ('custom', 'Personnalisé')], default='reminder', max_length=20)),
                ('category', models.CharField(choices=[('vendange', 'Vendanges'), ('lot', 'Lots techniques'), ('assemblage', 'Assemblages'), ('analyse', 'Analyses'), ('contenant', 'Contenants'), ('mise', 'Mises en bouteille'), ('parcelle', 'Parcelles'), ('general', 'Général')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('status', models.CharField(choices=[('active', 'Active'), ('snoozed', 'Reportée'), ('completed', 'Terminée'), ('dismissed', 'Ignorée')], default='active', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_type', models.CharField(blank=True, choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text="Type d'objet lié (Vendange, Lot, etc.)", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
    ]
