# Generated by Django 5.2.8 on 2026-01-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_alter_alert_id_alter_alert_object_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcelle',
        ),
    ]
