# Generated by Django 5.0.14 on 2025-09-22 08:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('stock', '0001_initial'),
        ('viticulture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('pro', 'Professionnel'), ('part', 'Particulier')], default='part', help_text='Type de client', max_length=4)),
                ('legal_name', models.CharField(help_text='Raison sociale ou nom complet', max_length=200)),
                ('vat_number', models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire (optionnel)', max_length=20)),
                ('billing_address', models.TextField(help_text='Adresse de facturation complète')),
                ('billing_postal_code', models.CharField(help_text='Code postal facturation', max_length=10)),
                ('billing_city', models.CharField(help_text='Ville facturation', max_length=100)),
                ('billing_country', models.CharField(default='FR', help_text='Pays facturation (ISO)', max_length=2)),
                ('shipping_address', models.TextField(blank=True, help_text='Adresse de livraison (si différente)')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=10)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_country', models.CharField(blank=True, max_length=2)),
                ('payment_terms', models.CharField(default='30j', help_text='Conditions de paiement (30j, comptant, etc.)', max_length=50)),
                ('currency', models.CharField(default='EUR', help_text='Devise par défaut', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Client actif')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nom de la grille tarifaire', max_length=100)),
                ('currency', models.CharField(default='EUR', help_text='Devise de la grille', max_length=3)),
                ('valid_from', models.DateField(help_text='Date de début de validité')),
                ('valid_to', models.DateField(blank=True, help_text='Date de fin de validité (optionnelle)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Grille active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_qty', models.PositiveIntegerField(blank=True, help_text='Quantité minimum pour ce prix (optionnel)', null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Remise en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sku', verbose_name='Produit (SKU)')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.pricelist', verbose_name='Grille tarifaire')),
            ],
            options={
                'verbose_name': 'Élément de prix',
                'verbose_name_plural': 'Éléments de prix',
                'ordering': ['sku', 'min_qty'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priorité (1 = plus haute priorité)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.pricelist')),
            ],
            options={
                'verbose_name': 'Grille client',
                'verbose_name_plural': 'Grilles clients',
                'ordering': ['customer', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='EUR', help_text='Devise du devis', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('lost', 'Perdu'), ('expired', 'Expiré')], default='draft', help_text='Statut du devis', max_length=10)),
                ('valid_until', models.DateField(help_text='Date limite de validité')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total HT', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total taxes', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total TTC', max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='sales.customer', verbose_name='Client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='EUR', help_text='Devise de la commande', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('fulfilled', 'Expédiée'), ('cancelled', 'Annulée')], default='draft', help_text='Statut de la commande', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Impayé'), ('partial', 'Partiellement payé'), ('paid', 'Payé'), ('refunded', 'Remboursé')], default='unpaid', help_text='Statut de paiement', max_length=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total HT', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total taxes', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total TTC', max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer', verbose_name='Client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.quote', verbose_name="Devis d'origine")),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_units', models.PositiveIntegerField(help_text='Quantité réservée', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.order', verbose_name='Commande')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.sku', verbose_name='Produit (SKU)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viticulture.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Réservation de stock',
                'verbose_name_plural': 'Réservations de stock',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Code court (TVA20, TVA10, etc.)', max_length=10)),
                ('name', models.CharField(help_text='Nom complet', max_length=100)),
                ('rate_pct', models.DecimalField(decimal_places=2, help_text='Taux en pourcentage (ex: 20.00 pour 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('country', models.CharField(default='FR', help_text='Code pays ISO (FR, DE, etc.)', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Code taxe actif')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Code taxe',
                'verbose_name_plural': 'Codes taxes',
                'ordering': ['country', 'rate_pct'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='Description du produit', max_length=200)),
                ('qty', models.PositiveIntegerField(help_text='Quantité', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire HT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Remise en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total HT de la ligne', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, help_text='Total taxes de la ligne', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, help_text='Total TTC de la ligne', max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quote', verbose_name='Devis')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.sku', verbose_name='Produit (SKU)')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.taxcode', verbose_name='Code taxe')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='Description du produit', max_length=200)),
                ('qty', models.PositiveIntegerField(help_text='Quantité', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire HT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Remise en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total HT de la ligne', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, help_text='Total taxes de la ligne', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, help_text='Total TTC de la ligne', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.order', verbose_name='Commande')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.sku', verbose_name='Produit (SKU)')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.taxcode', verbose_name='Code taxe')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'legal_name'], name='sales_custo_organiz_3392da_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'vat_number'], name='sales_custo_organiz_750d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'type'], name='sales_custo_organiz_0703b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'legal_name')},
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='priceitem',
            index=models.Index(fields=['price_list', 'sku', 'min_qty'], name='sales_price_price_l_d1aecf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='priceitem',
            unique_together={('price_list', 'sku', 'min_qty')},
        ),
        migrations.AlterUniqueTogether(
            name='customerpricelist',
            unique_together={('customer', 'price_list')},
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['organization', 'customer'], name='sales_quote_organiz_30e24d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['organization', 'status'], name='sales_quote_organiz_07ccce_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['organization', 'created_at'], name='sales_quote_organiz_85ecfe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'customer'], name='sales_order_organiz_ca24c8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status'], name='sales_order_organiz_81edc1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'created_at'], name='sales_order_organiz_7f8f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['organization', 'sku', 'warehouse'], name='sales_stock_organiz_193976_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['organization', 'order'], name='sales_stock_organiz_faa3ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockreservation',
            unique_together={('order', 'sku', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='taxcode',
            unique_together={('organization', 'code')},
        ),
    ]
