# Generated by Django 4.2.7 on 2025-11-03 19:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_alter_dashboardwidget_widget_type'),
        ('sales', '0003_remove_customer_sales_customer_segment_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom du preset (ex: 'Viticole bordeaux', 'Moderne épuré')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#8B1538', help_text='Couleur primaire (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#d4af37', help_text='Couleur secondaire (hex)', max_length=7)),
                ('text_color', models.CharField(default='#333333', help_text='Couleur du texte (hex)', max_length=7)),
                ('font_family', models.CharField(default='Georgia, serif', help_text='Police principale', max_length=200)),
                ('font_size_base', models.IntegerField(default=10, help_text='Taille de police de base (pt)')),
                ('logo_width', models.IntegerField(default=150, help_text='Largeur du logo (px)')),
                ('logo_position', models.CharField(choices=[('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite')], default='left', help_text='Position du logo', max_length=10)),
                ('generated_css', models.TextField(blank=True, help_text='CSS généré automatiquement à partir des paramètres')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_presets', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Preset de document',
                'verbose_name_plural': 'Presets de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom du template (ex: 'Devis standard', 'Facture viticole')", max_length=200)),
                ('document_type', models.CharField(choices=[('quote', 'Devis'), ('order', 'Commande'), ('invoice', 'Facture'), ('delivery', 'Bon de livraison'), ('proforma', 'Facture pro forma'), ('credit_note', 'Avoir'), ('receipt', 'Reçu'), ('estimate', 'Estimation')], help_text='Type de document', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description du template')),
                ('is_default', models.BooleanField(default=False, help_text='Template par défaut pour ce type de document')),
                ('is_active', models.BooleanField(default=True, help_text='Template actif')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('LETTER', 'Lettre US (216 x 279 mm)'), ('A5', 'A5 (148 x 210 mm)')], default='A4', help_text='Format papier', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Paysage')], default='portrait', help_text='Orientation', max_length=10)),
                ('margin_top', models.DecimalField(decimal_places=1, default=Decimal('20.0'), help_text='Marge haute (mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('margin_bottom', models.DecimalField(decimal_places=1, default=Decimal('20.0'), help_text='Marge basse (mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('margin_left', models.DecimalField(decimal_places=1, default=Decimal('20.0'), help_text='Marge gauche (mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('margin_right', models.DecimalField(decimal_places=1, default=Decimal('20.0'), help_text='Marge droite (mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('html_header', models.TextField(blank=True, help_text='En-tête HTML (logo, coordonnées, etc.)')),
                ('html_body', models.TextField(help_text='Corps du document HTML (avec variables)')),
                ('html_footer', models.TextField(blank=True, help_text='Pied de page HTML (mentions légales, CGV, etc.)')),
                ('custom_css', models.TextField(blank=True, help_text='Styles CSS personnalisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Template de document',
                'verbose_name_plural': 'Templates de documents',
                'ordering': ['document_type', '-is_default', 'name'],
                'indexes': [models.Index(fields=['organization', 'document_type', 'is_default'], name='sales_docum_organiz_7858d2_idx'), models.Index(fields=['organization', 'is_active'], name='sales_docum_organiz_0eefc2_idx')],
                'unique_together': {('organization', 'name', 'document_type')},
            },
        ),
    ]
