# Generated by Django 5.2.8 on 2025-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_documentpreset_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='blocks_config',
            field=models.JSONField(blank=True, default=None, help_text='Configuration JSON des blocs du builder visuel', null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='editor_mode',
            field=models.CharField(choices=[('blocks', 'Éditeur visuel (blocs)'), ('html', 'Éditeur HTML (avancé)')], default='blocks', help_text="Mode d'édition du template", max_length=10),
        ),
    ]
