# Generated by Django 5.2.8 on 2025-12-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_blocks_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpreset',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', help_text='Police principale', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
