# Generated by Django 5.2.8 on 2025-12-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('catalogue', '0004_article_purchase_price'),
        ('sales', '0006_alter_documentpreset_font_family_alter_pricelist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceitem',
            options={'ordering': ['article', 'min_qty'], 'verbose_name': 'Élément de prix', 'verbose_name_plural': 'Éléments de prix'},
        ),
        migrations.RemoveIndex(
            model_name='priceitem',
            name='sales_price_price_l_d1aecf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='priceitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.article', verbose_name='Article'),
        ),
        migrations.AddIndex(
            model_name='priceitem',
            index=models.Index(fields=['price_list', 'article', 'min_qty'], name='sales_price_price_l_7d20fd_idx'),
        ),
        migrations.RemoveField(
            model_name='priceitem',
            name='sku',
        ),
    ]
