# Generated by Django 5.2.8 on 2026-01-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_customer_alter_payment_customer'),
        ('partners', '0003_alter_contact_roles_alter_contactperson_partner_and_more'),
        ('produits', '0015_alter_purchasebatchbottle_supplier_and_more'),
        ('sales', '0007_alter_priceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpricelist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='partners.contact', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='partners.contact', verbose_name='Client'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
