# Generated by Django 5.2.8 on 2026-01-13 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0015_alter_purchasebatchbottle_supplier_and_more'),
        ('sales', '0008_alter_customerpricelist_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.product', verbose_name='Article'),
        ),
    ]
