# Generated by Django 5.2.8 on 2026-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_priceitem_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Image de fond du document (papier à en-tête)', null=True, upload_to='document_templates/backgrounds/'),
        ),
    ]
