# Generated by Django 5.0.14 on 2025-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_initialized',
            field=models.BooleanField(default=False, help_text='Exploitation initialisée via onboarding', verbose_name='Initialisé'),
        ),
    ]
