# Generated by Django 5.0.14 on 2025-09-20 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_is_initialized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adresse email de la personne invitée', max_length=254, verbose_name='Email destinataire')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('editor', 'Éditeur'), ('read_only', 'Lecture seule')], default='editor', help_text='Rôle à attribuer (editor par défaut)', max_length=20, verbose_name='Rôle proposé')),
                ('token', models.CharField(help_text='Token signé côté serveur, jamais prédictible', max_length=500, unique=True, verbose_name='Token signé')),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('accepted', 'Acceptée'), ('expired', 'Expirée')], default='sent', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(help_text='Expiration (ex: 72h selon roadmap)', verbose_name="Date d'expiration")),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Enregistrer accepted_at pour suivi', null=True, verbose_name="Date d'acceptation")),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Accepté par')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization', verbose_name='Organisation cible')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'indexes': [models.Index(fields=['email', 'status'], name='accounts_in_email_0582fe_idx'), models.Index(fields=['organization', 'status'], name='accounts_in_organiz_186540_idx'), models.Index(fields=['token'], name='accounts_in_token_be8e6c_idx')],
                'unique_together': {('email', 'organization', 'status')},
            },
        ),
    ]
