# Generated by Django 5.0.14 on 2025-09-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSetupChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict, help_text='État des 4 tâches: company_info, taxes, currency_format, terms', verbose_name='État des tâches')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_checklist', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Checklist d'onboarding",
                'verbose_name_plural': "Checklists d'onboarding",
                'db_table': 'accounts_org_setup_checklist',
            },
        ),
    ]
