# Generated by Django 5.0.14 on 2025-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_org_setup_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse fiscale complète', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, help_text='Ville', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='France', help_text='Pays', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Code postal', max_length=10, verbose_name='Code postal'),
        ),
    ]
