# Generated by Django 5.0.14 on 2025-09-20 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_address_fields_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Nom affiché dans l'interface (optionnel)", max_length=100, verbose_name="Nom d'affichage")),
                ('locale', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', help_text="Langue de l'interface", max_length=10, verbose_name='Langue')),
                ('timezone', models.CharField(default='Europe/Paris', help_text="Fuseau horaire pour l'affichage des dates", max_length=50, verbose_name='Fuseau horaire')),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil (max 2 Mo, formats JPG/PNG)', null=True, upload_to='avatars/%Y/%m/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateur',
                'db_table': 'accounts_user_profile',
            },
        ),
    ]
