# Generated by Django 5.0.14 on 2025-09-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Dénomination sociale officielle de votre organisation', max_length=200, verbose_name='Raison sociale')),
                ('billing_address_line1', models.CharField(help_text='Numéro et nom de rue', max_length=100, verbose_name='Adresse ligne 1')),
                ('billing_address_line2', models.CharField(blank=True, help_text="Complément d'adresse (optionnel)", max_length=100, verbose_name='Adresse ligne 2')),
                ('billing_postal_code', models.CharField(help_text='Code postal de facturation', max_length=10, verbose_name='Code postal')),
                ('billing_city', models.CharField(help_text='Ville de facturation', max_length=100, verbose_name='Ville')),
                ('billing_country', models.CharField(default='France', help_text='Pays de facturation', max_length=100, verbose_name='Pays')),
                ('siret', models.CharField(blank=True, help_text='Numéro SIRET (14 chiffres, si pertinent)', max_length=14, verbose_name='SIRET')),
                ('vat_status', models.CharField(choices=[('subject_to_vat', 'Assujetti à la TVA'), ('not_subject_to_vat', 'Non assujetti à la TVA')], help_text='Statut fiscal pour la TVA', max_length=20, verbose_name='Statut TVA')),
                ('vat_number', models.CharField(blank=True, help_text='Format FR + 11 chiffres (si assujetti à la TVA)', max_length=20, verbose_name='Numéro de TVA intracommunautaire')),
                ('billing_contact_name', models.CharField(blank=True, help_text='Personne responsable de la facturation (optionnel)', max_length=100, verbose_name='Nom du contact facturation')),
                ('billing_contact_email', models.EmailField(blank=True, help_text='Email pour les questions de facturation (optionnel)', max_length=254, verbose_name='Email du contact facturation')),
                ('billing_contact_phone', models.CharField(blank=True, help_text='Numéro de téléphone du contact (optionnel)', max_length=20, verbose_name='Téléphone du contact facturation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Informations de facturation',
                'verbose_name_plural': 'Informations de facturation',
                'db_table': 'accounts_org_billing',
            },
        ),
    ]
