# Generated by Django 5.0.14 on 2025-09-20 09:34

from django.db import migrations


def create_billing_for_existing_orgs(apps, schema_editor):
    """
    Créer des enregistrements OrgBilling vides pour toutes les organisations existantes
    Migration de données selon roadmap 11 - Étape 1.2
    """
    Organization = apps.get_model('accounts', 'Organization')
    OrgBilling = apps.get_model('accounts', 'OrgBilling')
    
    for org in Organization.objects.all():
        # Créer un enregistrement de facturation vide si il n'existe pas déjà
        if not hasattr(org, 'billing'):
            OrgBilling.objects.create(
                organization=org,
                legal_name='',  # Sera rempli par l'admin
                billing_address_line1='',
                billing_postal_code='',
                billing_city='',
                billing_country='France',
                vat_status='not_subject_to_vat',  # Valeur par défaut sûre
            )


def reverse_create_billing_for_existing_orgs(apps, schema_editor):
    """Supprimer tous les enregistrements OrgBilling créés"""
    OrgBilling = apps.get_model('accounts', 'OrgBilling')
    OrgBilling.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_create_org_billing'),
    ]

    operations = [
        migrations.RunPython(
            create_billing_for_existing_orgs,
            reverse_create_billing_for_existing_orgs
        ),
    ]
