# Generated by Django 5.0.14 on 2025-09-21 06:36

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_create_billing_for_existing_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('GBP', 'Livre Sterling (£)'), ('CHF', 'Franc Suisse (CHF)')], default='EUR', max_length=3, verbose_name='Devise')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY (31/12/2025)'), ('MM/DD/YYYY', 'MM/DD/YYYY (12/31/2025)'), ('YYYY-MM-DD', 'YYYY-MM-DD (2025-12-31)')], default='DD/MM/YYYY', max_length=10, verbose_name='Format de date')),
                ('number_format', models.CharField(choices=[('FR', '1 234,56 (français)'), ('EN', '1,234.56 (anglais)')], default='FR', max_length=2, verbose_name='Format des nombres')),
                ('terms_url', models.URLField(blank=True, verbose_name='URL des CGV')),
                ('terms_file', models.FileField(blank=True, upload_to='terms/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.accounts.models.validate_pdf_size], verbose_name='Fichier CGV (PDF)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Paramètres organisation',
                'verbose_name_plural': 'Paramètres organisations',
            },
        ),
    ]
