# Generated by Django 4.2.7 on 2025-10-30 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code unique du widget', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom du widget', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du widget')),
                ('widget_type', models.CharField(choices=[('metric', 'Métrique'), ('chart', 'Graphique'), ('list', 'Liste'), ('shortcut', 'Raccourci')], default='metric', max_length=20)),
                ('icon', models.CharField(default='bi-graph-up', help_text='Icône Bootstrap', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Widget Dashboard',
                'verbose_name_plural': 'Widgets Dashboard',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_widgets', models.JSONField(default=list, help_text="Liste des codes de widgets actifs dans l'ordre d'affichage")),
                ('custom_shortcuts', models.JSONField(default=list, help_text='Raccourcis personnalisés [{name, url, icon, color}]')),
                ('layout', models.CharField(choices=[('grid', 'Grille'), ('list', 'Liste')], default='grid', max_length=20)),
                ('columns', models.IntegerField(default=3, help_text='Nombre de colonnes (1-4)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Dashboard',
                'verbose_name_plural': 'Configurations Dashboard',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
