# Generated by Django 4.2.7 on 2025-10-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_dashboardwidget_userdashboardconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('metric', 'Métrique'), ('chart', 'Graphique'), ('list', 'Liste'), ('shortcut', 'Raccourci'), ('alert', 'Alerte')], default='metric', max_length=20),
        ),
    ]
