# Generated by Django 5.2.8 on 2025-11-23 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_dashboardwidget_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('icon', models.CharField(default='bi-star-fill', max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='text-warning', max_length=20, verbose_name='Couleur')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raccourci utilisateur',
                'verbose_name_plural': 'Raccourcis utilisateur',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
