# Generated by Django 5.2.8 on 2025-11-25 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usershortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='siret',
            field=models.CharField(blank=True, help_text='Numéro SIRET à 14 chiffres (optionnel)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Le SIRET doit contenir 14 chiffres')], verbose_name='SIRET'),
        ),
    ]
