# Generated by Django 5.2.8 on 2025-11-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_make_siret_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Code court à partager (ex: ABC123)', max_length=8, null=True, unique=True, verbose_name="Code d'invitation"),
        ),
    ]
