# Generated by Django 5.2.8 on 2025-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permissions par module: parcelles, cuvees, vendanges, lots, stocks, ventes, factures, stats', verbose_name='Permissions détaillées'),
        ),
    ]
