# Generated by Django 5.2.8 on 2025-11-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_membership_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.CharField(default='#722F37', help_text='Couleur distinctive du chai (hex, ex: #722F37)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Marque ce chai comme environnement de test', verbose_name='Chai de test'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_org',
            field=models.ForeignKey(blank=True, help_text='Chai a ouvrir automatiquement a la connexion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='accounts.organization', verbose_name='Chai par defaut'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_by_users', to='accounts.organization', verbose_name='Dernier chai utilise'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_preference',
            field=models.CharField(choices=[('last_used', 'Dernier chai utilise'), ('always_ask', 'Toujours demander'), ('default', 'Toujours ouvrir le chai par defaut')], default='last_used', max_length=20, verbose_name='Preference de chai'),
        ),
    ]
