# Generated by Django 5.2.8 on 2025-11-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_ux_multi_chai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
