# Generated by Django 5.2.8 on 2025-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_fix_dashboard_config_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region_viticole',
            field=models.CharField(blank=True, choices=[('', '-- Non spécifiée --'), ('bordeaux', 'Bordeaux'), ('bourgogne', 'Bourgogne'), ('alsace', 'Alsace'), ('champagne', 'Champagne'), ('loire', 'Val de Loire'), ('rhone', 'Vallée du Rhône'), ('provence', 'Provence'), ('languedoc', 'Languedoc-Roussillon'), ('sud_ouest', 'Sud-Ouest'), ('jura', 'Jura'), ('savoie', 'Savoie'), ('corse', 'Corse'), ('beaujolais', 'Beaujolais')], default='', help_text='Région viticole principale pour préfiltrer les cépages', max_length=20, verbose_name='Région viticole'),
        ),
    ]
