# Generated by Django 5.2.8 on 2025-12-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date', models.DateField(verbose_name='Date de facturation')),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('amount_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('status', models.CharField(choices=[('paid', 'Payée'), ('pending', 'En attente'), ('failed', 'Échouée')], default='pending', max_length=20, verbose_name='Statut')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Facture PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'accounts_invoice',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('discovery', 'Découverte (Gratuit)'), ('vigneron', "Vigneron (Jusqu'à 20ha)"), ('domain', 'Domaine (Illimité)')], default='discovery', max_length=50, verbose_name='Nom du plan')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('past_due', 'En retard de paiement'), ('canceled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant mensuel (HT)')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Date de renouvellement')),
                ('payment_method_summary', models.CharField(blank=True, help_text='Ex: Visa terminaison 4242', max_length=100, verbose_name='Moyen de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'accounts_subscription',
            },
        ),
    ]
