# Generated by Django 5.0.14 on 2025-09-21 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('metadata', '0001_initial_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom humain de l'entité", max_length=100)),
                ('code', models.CharField(help_text='Code technique unique', max_length=50)),
                ('domain', models.CharField(choices=[('viticulture', 'Viticulture'), ('production', 'Production'), ('commercial', 'Commercial'), ('finance', 'Finance'), ('referentiel', 'Référentiel'), ('system', 'Système')], help_text='Domaine métier', max_length=20)),
                ('is_searchable', models.BooleanField(default=True, help_text='Inclure dans la recherche globale')),
                ('is_listable', models.BooleanField(default=True, help_text='Affichable dans les listes')),
                ('description', models.TextField(blank=True, help_text="Description de l'entité")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('content_type', models.ForeignKey(help_text='Type de contenu Django correspondant', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, help_text='Organisation propriétaire, null pour entités système', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_entities', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Entité métier',
                'verbose_name_plural': 'Entités métier',
                'ordering': ['domain', 'name'],
                'unique_together': {('content_type',), ('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MetaAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom humain de l'attribut", max_length=100)),
                ('code', models.CharField(help_text='Nom du champ en base', max_length=50)),
                ('data_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('decimal', 'Décimal'), ('boolean', 'Booléen'), ('date', 'Date'), ('datetime', 'Date et heure'), ('choice', 'Choix (énumération)'), ('reference', 'Référence vers entité'), ('json', 'JSON'), ('file', 'Fichier')], max_length=20)),
                ('is_nullable', models.BooleanField(default=True, help_text='Peut être null')),
                ('unit', models.CharField(blank=True, help_text='Unité (kg, L, °C, etc.)', max_length=20)),
                ('is_facet', models.BooleanField(default=False, help_text='Utilisable comme facette de filtrage')),
                ('is_sortable', models.BooleanField(default=False, help_text='Utilisable pour le tri')),
                ('is_fulltext', models.BooleanField(default=False, help_text='Inclure dans la recherche textuelle')),
                ('is_required', models.BooleanField(default=False, help_text='Champ obligatoire')),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('help_text', models.TextField(blank=True, help_text='Aide contextuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='metadata.metaentity')),
                ('ref_entity', models.ForeignKey(blank=True, help_text='Entité référencée si type=reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='metadata.metaentity')),
            ],
            options={
                'verbose_name': 'Attribut métier',
                'verbose_name_plural': 'Attributs métier',
                'ordering': ['entity', 'display_order', 'name'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MetaRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom de la règle', max_length=100)),
                ('rule_type', models.CharField(choices=[('regex', 'Expression régulière'), ('range', 'Plage de valeurs'), ('length', 'Longueur'), ('format', 'Format spécifique'), ('reference', 'Intégrité référentielle'), ('business', 'Règle métier'), ('custom', 'Règle personnalisée')], max_length=20)),
                ('rule_config', models.JSONField(help_text='Configuration de la règle (regex, min/max, etc.)')),
                ('severity', models.CharField(choices=[('error', 'Erreur (bloquant)'), ('warning', 'Avertissement'), ('info', 'Information')], default='warning', max_length=10)),
                ('error_message', models.TextField(help_text="Message d'erreur à afficher")),
                ('is_active', models.BooleanField(default=True)),
                ('check_on_save', models.BooleanField(default=True, help_text='Vérifier à la sauvegarde')),
                ('check_on_batch', models.BooleanField(default=True, help_text='Vérifier en batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(blank=True, help_text="Attribut concerné, null pour règles sur l'entité complète", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='metadata.metaattribute')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='metadata.metaentity')),
            ],
            options={
                'verbose_name': 'Règle de qualité',
                'verbose_name_plural': 'Règles de qualité',
                'ordering': ['entity', 'attribute', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetaEnum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='Valeur technique stockée', max_length=100)),
                ('label', models.CharField(help_text="Libellé affiché à l'utilisateur", max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, help_text='Couleur hexadécimale #RRGGBB', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône Bootstrap", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(limit_choices_to={'data_type': 'choice'}, on_delete=django.db.models.deletion.CASCADE, related_name='enum_values', to='metadata.metaattribute')),
            ],
            options={
                'verbose_name': 'Valeur énumérée',
                'verbose_name_plural': 'Valeurs énumérées',
                'ordering': ['attribute', 'display_order', 'label'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='MetaGlossary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(help_text='Terme métier', max_length=100)),
                ('definition', models.TextField(help_text='Définition complète')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='Liste des synonymes')),
                ('abbreviations', models.JSONField(blank=True, default=list, help_text='Abréviations courantes')),
                ('domain', models.CharField(blank=True, help_text='Domaine métier', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags de classification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='accounts.organization')),
                ('related_entities', models.ManyToManyField(blank=True, help_text='Entités liées à ce terme', related_name='glossary_terms', to='metadata.metaentity')),
            ],
            options={
                'verbose_name': 'Terme du glossaire',
                'verbose_name_plural': 'Termes du glossaire',
                'ordering': ['term'],
                'unique_together': {('organization', 'term', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MetaRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('one_to_one', 'Un vers un'), ('one_to_many', 'Un vers plusieurs'), ('many_to_many', 'Plusieurs vers plusieurs'), ('inheritance', 'Héritage'), ('composition', 'Composition'), ('aggregation', 'Agrégation')], max_length=20)),
                ('source_name', models.CharField(help_text='Nom de la relation côté source', max_length=50)),
                ('target_name', models.CharField(help_text='Nom de la relation côté cible', max_length=50)),
                ('is_navigable_forward', models.BooleanField(default=True, help_text='Navigation source → cible')),
                ('is_navigable_backward', models.BooleanField(default=True, help_text='Navigation cible → source')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='metadata.metaentity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='metadata.metaentity')),
            ],
            options={
                'verbose_name': 'Relation métier',
                'verbose_name_plural': 'Relations métier',
                'ordering': ['source_entity', 'target_entity'],
                'unique_together': {('source_entity', 'target_entity', 'source_name')},
            },
        ),
    ]
