# Generated by Django 5.0.14 on 2025-09-21 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('metadata', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du flag (ex: search_v2_read)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description du flag et son impact')),
                ('is_enabled', models.BooleanField(default=False, help_text='Flag activé globalement')),
                ('rollout_percentage', models.PositiveIntegerField(default=0, help_text="Pourcentage d'utilisateurs avec ce flag (0-100)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_organizations', models.ManyToManyField(blank=True, help_text='Organisations avec ce flag activé (si vide = global)', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_version', models.CharField(choices=[('v1', 'Recherche V1 (actuelle)'), ('v2', 'Recherche V2 (FTS + trigram)')], default='v1', max_length=10)),
                ('query_hash', models.CharField(help_text='Hash MD5 de la requête (pas de PII)', max_length=64)),
                ('entity_type', models.CharField(help_text="Type d'entité recherchée", max_length=50)),
                ('result_count', models.PositiveIntegerField(help_text='Nombre de résultats')),
                ('has_results', models.BooleanField(help_text='Au moins 1 résultat')),
                ('elapsed_ms', models.PositiveIntegerField(help_text='Temps de réponse en ms')),
                ('cache_hit', models.BooleanField(default=False, help_text='Résultat depuis le cache')),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('is_live_search', models.BooleanField(default=False, help_text='Recherche en temps réel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Métrique de recherche',
                'verbose_name_plural': 'Métriques de recherche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'engine_version', 'created_at'], name='metadata_se_organiz_78d40d_idx'), models.Index(fields=['entity_type', 'has_results'], name='metadata_se_entity__2a4d29_idx'), models.Index(fields=['elapsed_ms'], name='metadata_se_elapsed_2e9245_idx')],
            },
        ),
    ]
