# Generated by Django 5.0.14 on 2025-09-08 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('capacite_hl', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Capacité (hl)')),
                ('materiau', models.CharField(choices=[('inox', 'Inox'), ('beton', 'Béton'), ('bois', 'Bois'), ('fibre', 'Fibre'), ('autre', 'Autre')], default='inox', max_length=10, verbose_name='Matériau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves', to='accounts.domaine')),
            ],
            options={
                'verbose_name': 'Cuve',
                'verbose_name_plural': 'Cuves',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_disponible_hl', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume disponible (hl)')),
                ('ref_interne', models.CharField(blank=True, max_length=100, verbose_name='Référence interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.cuve')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounts.domaine')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
            },
        ),
        migrations.CreateModel(
            name='BouteilleLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_bouteilles', models.PositiveIntegerField(verbose_name='Nombre de bouteilles')),
                ('contenance_ml', models.PositiveIntegerField(verbose_name='Contenance (ml)')),
                ('date', models.DateField(verbose_name='Date de mise en bouteille')),
                ('ref_interne', models.CharField(blank=True, max_length=100, verbose_name='Référence interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouteille_lots', to='accounts.domaine')),
                ('source_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouteille_lots', to='core.lot')),
            ],
            options={
                'verbose_name': 'Lot de bouteilles',
                'verbose_name_plural': 'Lots de bouteilles',
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vendange_vers_cuve', 'Vendange vers cuve'), ('inter_cuves', 'Inter-cuves'), ('perte', 'Perte'), ('mise_en_bouteille', 'Mise en bouteille'), ('vente_sortie_stock', 'Vente sortie stock'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('volume_hl', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume (hl)')),
                ('pertes_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pertes (hl)')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('valide', 'Validé'), ('verrouille', 'Verrouillé')], default='draft', max_length=10, verbose_name='Statut')),
                ('verrouille', models.BooleanField(default=False, verbose_name='Verrouillé')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('meta_json', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('destination_cuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_destination', to='core.cuve')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='accounts.domaine')),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_source', to='core.lot')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('cepage', models.CharField(max_length=100, verbose_name='Cépage')),
                ('surface_ha', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Surface (ha)')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('annee_plantation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de plantation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='accounts.domaine')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
            },
        ),
        migrations.CreateModel(
            name='Vendange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de vendange')),
                ('volume_hl', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume (hl)')),
                ('dechets_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déchets (hl)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendanges', to='core.parcelle')),
            ],
            options={
                'verbose_name': 'Vendange',
                'verbose_name_plural': 'Vendanges',
            },
        ),
    ]
