# Generated by Django 5.0.14 on 2025-09-16 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='produit_id',
            field=models.PositiveIntegerField(blank=True, help_text='Pour les mouvements de vente', null=True, verbose_name='ID Produit'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='verrouille',
            field=models.BooleanField(verbose_name='Verrouillé'),
        ),
        migrations.AlterField(
            model_name='vendange',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vendange',
            name='dechets_hl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déchets (HL)'),
        ),
        migrations.AlterField(
            model_name='vendange',
            name='volume_hl',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume (HL)'),
        ),
    ]
