# Generated by Django 5.0.14 on 2025-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mouvement_produit_id_alter_mouvement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='verrouille',
            field=models.BooleanField(default=False, verbose_name='Verrouillé'),
        ),
    ]
