# Generated by Django 5.0.14 on 2025-09-22 09:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('sales', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Numéro de facture (généré automatiquement)', max_length=20)),
                ('date_issue', models.DateField(default=django.utils.timezone.now, help_text="Date d'émission")),
                ('due_date', models.DateField(help_text="Date d'échéance")),
                ('currency', models.CharField(default='EUR', help_text='Devise', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', help_text='Statut de la facture', max_length=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total HT', max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total TVA', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total TTC', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer', verbose_name='Client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.order', verbose_name="Commande d'origine")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_issue', '-number'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text="Numéro d'avoir (généré automatiquement)", max_length=20)),
                ('date_issue', models.DateField(default=django.utils.timezone.now, help_text="Date d'émission")),
                ('reason', models.CharField(help_text="Motif de l'avoir", max_length=200)),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total HT (négatif)', max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, help_text='Total TVA (négatif)', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, help_text='Total TTC (négatif)', max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.invoice', verbose_name="Facture d'origine")),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date_issue', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='Description', max_length=200)),
                ('qty', models.DecimalField(decimal_places=3, help_text='Quantité', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire HT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Remise en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total HT de la ligne', max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, help_text='Total TVA de la ligne', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, help_text='Total TTC de la ligne', max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice', verbose_name='Facture')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.sku', verbose_name='Produit (SKU)')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.taxcode', verbose_name='Code TVA')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('sepa', 'Virement SEPA'), ('card', 'Carte bancaire'), ('cheque', 'Chèque'), ('cash', 'Espèces'), ('transfer', 'Virement')], help_text='Méthode de paiement', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant encaissé', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='EUR', help_text='Devise', max_length=3)),
                ('date_received', models.DateField(default=django.utils.timezone.now, help_text='Date de réception')),
                ('reference', models.CharField(blank=True, help_text='Référence du paiement (chèque, virement, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customer', verbose_name='Client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, help_text='Montant alloué', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='billing.invoice', verbose_name='Facture')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='billing.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Réconciliation',
                'verbose_name_plural': 'Réconciliations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_type', models.CharField(choices=[('product', 'Produit'), ('customer', 'Client'), ('tax', 'Taxe'), ('payment_method', 'Méthode de paiement')], help_text='Type de mapping', max_length=20)),
                ('key', models.CharField(help_text='Clé de référence (ID produit, code taxe, etc.)', max_length=50)),
                ('account_code', models.CharField(help_text='Code compte comptable', max_length=10)),
                ('account_name', models.CharField(help_text='Libellé du compte', max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'ordering': ['mapping_type', 'account_code'],
                'unique_together': {('organization', 'mapping_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='GLEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.CharField(choices=[('VEN', 'Ventes'), ('BAN', 'Banque'), ('OD', 'Opérations diverses')], help_text='Code journal', max_length=3)),
                ('date', models.DateField(help_text='Date comptable')),
                ('doc_type', models.CharField(choices=[('invoice', 'Facture'), ('payment', 'Paiement'), ('credit_note', 'Avoir')], help_text='Type de document', max_length=15)),
                ('doc_id', models.UUIDField(help_text='ID du document source')),
                ('doc_number', models.CharField(help_text='Numéro du document', max_length=20)),
                ('account_code', models.CharField(help_text='Code compte comptable', max_length=10)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant débit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant crédit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('label', models.CharField(help_text="Libellé de l'écriture", max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', 'journal', 'doc_number'],
                'indexes': [models.Index(fields=['organization', 'journal', 'date'], name='billing_gle_organiz_e5d742_idx'), models.Index(fields=['organization', 'account_code', 'date'], name='billing_gle_organiz_03e040_idx'), models.Index(fields=['organization', 'doc_type', 'doc_id'], name='billing_gle_organiz_a62ab6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'customer', 'date_issue'], name='billing_inv_organiz_3da1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'date_issue'], name='billing_inv_organiz_490245_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'number'], name='billing_inv_organiz_39cb25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('organization', 'number')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'customer', 'date_received'], name='billing_pay_organiz_ad961d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'method', 'date_received'], name='billing_pay_organiz_ec7699_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliation',
            unique_together={('payment', 'invoice')},
        ),
    ]
