# Generated by Django 5.0.14 on 2025-09-29 18:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('produits', '0003_miseligne_volume_l'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='produits_in_organiz_9e83aa_idx',
            old_name='prod_inv_org_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='produits_pr_organiz_9e055d_idx',
            old_name='prod_prod_org_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='produits_pr_organiz_49bcf4_idx',
            old_name='prod_prod_org_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='sku',
            new_name='produits_sk_organiz_65689d_idx',
            old_name='prod_sku_org_prod_active_idx',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='default_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
    ]
