# Generated by Django 4.2.7 on 2025-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_mise_add_execution_token_and_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mise',
            name='state',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('terminee', 'Terminée')], default='brouillon', max_length=16),
        ),
    ]
