# Generated by Django 4.2.7 on 2025-10-16 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viticulture', '0006_alter_lotintervention_type_lotmeasurement'),
        ('accounts', '0010_create_default_orgsettings'),
        ('referentiels', '0004_rename_referentiels_cepage_org_name_norm_idx_referentiel_organiz_49d2b6_idx'),
        ('sales', '0001_initial'),
        ('produits', '0006_alter_mise_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, max_length=250, verbose_name='Allergènes / mentions'),
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité (pers.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dluo',
            field=models.DateField(blank=True, null=True, verbose_name='DLUO/DLC'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Durée (h/j)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=64, verbose_name='Code EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.CharField(blank=True, max_length=50, verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_content',
            field=models.CharField(blank=True, max_length=50, verbose_name='Poids/Volume unitaire'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_eur_u',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente (€ / u)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('vin', 'Vin'), ('produit', 'Produit dérivé'), ('service', 'Service')], default='vin', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='service_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Catégorie service'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_mode',
            field=models.CharField(choices=[('domaine', 'Domaine (interne)'), ('negoce_vrac', 'Négoce (vrac)'), ('negoce_bout', 'Négoce (bouteilles)'), ('libre', 'Libre (sans source)')], default='domaine', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stockable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiels.unite', verbose_name='Unité de vente'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Volume par unité (L)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom / Étiquette'),
        ),
        migrations.CreateModel(
            name='PurchaseBatchVrac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vintage', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_eur_hl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_ref', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('appellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viticulture.appellation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseBatchBottle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_label', models.CharField(max_length=200)),
                ('ean_supplier', models.CharField(blank=True, max_length=64)),
                ('qty_u', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_eur_u', models.DecimalField(decimal_places=4, max_digits=10)),
                ('received_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiels.unite')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductSourcingVrac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fifo', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_vrac', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSourcingCuvee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratio_pct', models.DecimalField(decimal_places=3, default=100, max_digits=6, verbose_name='Ratio (%)')),
                ('allow_other_vintages', models.BooleanField(default=False)),
                ('cuvee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viticulture.cuvee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_cuvees', to='produits.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductSourcingBottle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ean_override', models.CharField(blank=True, max_length=64, verbose_name='EAN interne (override)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_bottle', to='produits.product')),
            ],
        ),
    ]
