# Generated by Django 4.2.7 on 2025-10-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_product_allergens_product_capacity_product_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotcommercial',
            name='capsule_crd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='capsule_crd_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='capsule_marking',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='emb_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='inao_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
