# Generated by Django 4.2.7 on 2025-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_lotcommercial_capsule_crd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotcommercial',
            name='nc_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
