# Generated by Django 5.2.8 on 2025-12-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('produits', '0010_alter_inventoryitem_id_alter_product_id_alter_sku_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotcommercial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='etiquetage',
            field=models.CharField(choices=[('non_etiquete', 'Non étiqueté'), ('etiquete', 'Étiqueté'), ('partiel', 'Partiellement étiqueté')], default='non_etiquete', max_length=20),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots_commerciaux', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='lotcommercial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotcommercial',
            name='date_mise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotcommercial',
            name='mise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='produits.mise'),
        ),
        migrations.AlterField(
            model_name='lotcommercial',
            name='quantite_unites',
            field=models.PositiveIntegerField(default=0, help_text='Quantité initiale produite'),
        ),
        migrations.AlterField(
            model_name='lotcommercial',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0, help_text='Stock restant disponible'),
        ),
    ]
