# Generated by Django 5.2.8 on 2025-12-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_lot_commercial_etiquetage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
