# Generated by Django 5.2.8 on 2025-12-13 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('produits', '0012_alter_inventoryitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement')], max_length=20)),
                ('source_doc_type', models.CharField(blank=True, max_length=50)),
                ('source_doc_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='produits.sku')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
