# Generated by Django 5.2.8 on 2025-12-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('produits', '0013_stockmovement'),
        ('referentiels', '0012_cepage_couleur_libre_alter_cepage_couleur_and_more'),
        ('sales', '0006_alter_documentpreset_font_family_alter_pricelist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_buyable',
            field=models.BooleanField(default=False, help_text='Peut être acheté (Profil Achat)', verbose_name='Achetable'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_consumable',
            field=models.BooleanField(default=False, help_text='Pour usage interne (ne pas revendre)', verbose_name='Consommable'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=False, help_text='Peut être vendu (Profil Vente)', verbose_name='Vendable'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='PurchaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='Fournisseur principal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseprofile', to='produits.product')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiels.unite', verbose_name="Unité d'achat")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_name', models.CharField(blank=True, help_text='Si différent du nom interne', max_length=150, verbose_name='Nom commercial')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente (€ / u)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA (%)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesprofile', to='produits.product')),
                ('sales_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiels.unite', verbose_name='Unité de vente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
