# Generated by Django 5.2.8 on 2026-01-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_contact_roles_alter_contactperson_partner_and_more'),
        ('produits', '0014_product_is_buyable_product_is_consumable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebatchbottle',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.contact'),
        ),
        migrations.AlterField(
            model_name='purchasebatchvrac',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.contact'),
        ),
        migrations.AlterField(
            model_name='purchaseprofile',
            name='main_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.contact', verbose_name='Fournisseur principal'),
        ),
    ]
