# Generated by Django 5.2.8 on 2026-01-13 07:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_invoice_subscription'),
        ('partners', '0003_alter_contact_roles_alter_contactperson_partner_and_more'),
        ('produits', '0015_alter_purchasebatchbottle_supplier_and_more'),
        ('referentiels', '0012_cepage_couleur_libre_alter_cepage_couleur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_categories', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='produits.supplycategory', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de fourniture',
                'verbose_name_plural': 'Catégories de fournitures',
                'db_table': 'produits_supply_category',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('raw_material', 'Matière première'), ('consumable', 'Consommable'), ('packaging', 'Emballage'), ('oenological', 'Produit œnologique'), ('equipment', 'Équipement'), ('service', 'Service / Prestation'), ('other', 'Autre')], default='consumable', max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('reference', models.CharField(blank=True, help_text='Code article interne', max_length=50, verbose_name='Référence interne')),
                ('supplier_ref', models.CharField(blank=True, help_text='Référence chez le fournisseur', max_length=50, verbose_name='Réf. fournisseur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('packaging_qty', models.DecimalField(decimal_places=2, default=1, help_text='Ex: 1000 bouchons par carton', max_digits=10, verbose_name='Qté par conditionnement')),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Qté min. commande')),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat HT")),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA (%)')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=4, help_text="Dernier prix d'achat constaté", max_digits=10, null=True, verbose_name='Dernier PA')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Date dernier achat')),
                ('is_stockable', models.BooleanField(default=True, help_text='Si actif, le système suit les quantités', verbose_name='Géré en stock')),
                ('stock_min', models.DecimalField(decimal_places=2, default=0, help_text="Seuil d'alerte stock bas", max_digits=10, verbose_name='Stock minimum')),
                ('stock_max', models.DecimalField(decimal_places=2, default=0, help_text='Stock cible (0 = pas de limite)', max_digits=10, verbose_name='Stock maximum')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Délai de réapprovisionnement moyen', verbose_name='Délai appro. (jours)')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Caractéristiques techniques (dimensions, matière, etc.)', verbose_name='Spécifications')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_discontinued', models.BooleanField(default=False, help_text='Produit arrêté, ne plus commander', verbose_name='Arrêté')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('main_supplier', models.ForeignKey(blank=True, limit_choices_to={'roles__code': 'FOURNISSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='partners.contact', verbose_name='Fournisseur principal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='accounts.organization')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='referentiels.unite', verbose_name="Unité d'achat")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='produits.supplycategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Fourniture',
                'verbose_name_plural': 'Fournitures',
                'db_table': 'produits_supply',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée (Réception)'), ('out', 'Sortie (Consommation)'), ('adjust', 'Ajustement (Inventaire)'), ('transfer', 'Transfert')], max_length=10, verbose_name='Type')),
                ('reason', models.CharField(choices=[('purchase', 'Achat / Réception'), ('production', 'Production'), ('return', 'Retour fournisseur'), ('loss', 'Perte / Casse'), ('inventory', 'Inventaire'), ('transfer', 'Transfert interne'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Motif')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('batch_number', models.CharField(blank=True, default='', max_length=50, verbose_name='N° lot')),
                ('reference', models.CharField(blank=True, help_text='Ex: Bon réception #123, OF #456', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_movements_in', to='referentiels.entrepot', verbose_name='Destination')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_movements', to='referentiels.entrepot', verbose_name='Emplacement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_movements', to='accounts.organization')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='produits.supply')),
            ],
            options={
                'verbose_name': 'Mouvement fourniture',
                'verbose_name_plural': 'Mouvements fournitures',
                'db_table': 'produits_supply_movement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, default='', max_length=50, verbose_name='N° de lot')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité')),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, help_text='Quantité réservée pour production', max_digits=12, verbose_name='Qté réservée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_stocks', to='referentiels.entrepot', verbose_name='Emplacement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_stocks', to='accounts.organization')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lines', to='produits.supply')),
            ],
            options={
                'verbose_name': 'Stock fourniture',
                'verbose_name_plural': 'Stocks fournitures',
                'db_table': 'produits_supply_stock',
                'ordering': ['supply', 'location'],
            },
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['organization', 'supply_type', 'is_active'], name='produits_su_organiz_c4d1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['organization', 'reference'], name='produits_su_organiz_a504c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('organization', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='supplystock',
            unique_together={('supply', 'location', 'batch_number')},
        ),
    ]
