# Generated by Django 4.2.7 on 2025-10-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parcelle',
            new_name='giscore_par_tenant__1aea21_idx',
            old_name='giscore_par_tenant__idx',
        ),
    ]
