# Generated by Django 5.0.14 on 2025-09-08 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRMExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format : YYYY-MM (ex: 2025-09)', max_length=7, verbose_name='Période')),
                ('chemin_csv', models.CharField(max_length=255, verbose_name='Chemin du CSV')),
                ('chemin_pdf', models.CharField(max_length=255, verbose_name='Chemin du PDF')),
                ('checksums', models.JSONField(default=dict, verbose_name='Checksums')),
                ('data', models.JSONField(default=dict, verbose_name='Données exportées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drm_exports', to='accounts.domaine')),
            ],
            options={
                'verbose_name': 'Export DRM',
                'verbose_name_plural': 'Exports DRM',
                'unique_together': {('domaine', 'periode')},
            },
        ),
    ]
