# Generated by Django 5.0.14 on 2025-09-16 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drmexport',
            options={'ordering': ['-periode', '-created_at'], 'verbose_name': 'Export DRM', 'verbose_name_plural': 'Exports DRM'},
        ),
        migrations.AddField(
            model_name='drmexport',
            name='entrees_hl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Entrées (HL)'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='pertes_hl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pertes (HL)'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='region',
            field=models.CharField(default='Loire', help_text="Région viticole pour l'export DRM", max_length=50, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='sorties_hl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sorties (HL)'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('genere', 'Généré'), ('transmis', 'Transmis'), ('valide', 'Validé')], default='brouillon', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='stock_debut_hl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock début (HL)'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='stock_fin_hl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock fin (HL)'),
        ),
        migrations.AddField(
            model_name='drmexport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='drmexport',
            name='chemin_csv',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chemin du CSV'),
        ),
        migrations.AlterField(
            model_name='drmexport',
            name='chemin_pdf',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chemin du PDF'),
        ),
        migrations.CreateModel(
            name='DRMLigneProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellation', models.CharField(max_length=100, verbose_name='Appellation')),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé'), ('autre', 'Autre')], max_length=20, verbose_name='Couleur')),
                ('stock_debut_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock début (HL)')),
                ('entrees_vendange_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrées vendange (HL)')),
                ('entrees_autres_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres entrées (HL)')),
                ('sorties_vente_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sorties vente (HL)')),
                ('sorties_autres_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres sorties (HL)')),
                ('pertes_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pertes (HL)')),
                ('stock_fin_hl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock fin (HL)')),
                ('references_lots', models.JSONField(default=list, verbose_name='Références des lots')),
                ('drm_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_produits', to='drm.drmexport')),
            ],
            options={
                'verbose_name': 'Ligne produit DRM',
                'verbose_name_plural': 'Lignes produits DRM',
                'unique_together': {('drm_export', 'appellation', 'couleur')},
            },
        ),
    ]
