# Generated by Django 5.0.14 on 2025-09-22 07:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('viticulture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume_by_uom_to_l', models.DecimalField(decimal_places=4, help_text="Volume d'une unité convertie en litres (ex: 0.75 pour une bouteille)", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Volume unitaire en litres')),
                ('label', models.CharField(help_text='Nom commercial du produit fini', max_length=200, verbose_name='Étiquette')),
                ('code_barres', models.CharField(blank=True, help_text='Code-barres EAN13 ou autre', max_length=50, verbose_name='Code-barres')),
                ('is_active', models.BooleanField(default=True, help_text='SKU en production active', verbose_name='Actif')),
                ('cuvee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.cuvee', verbose_name='Cuvée')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.unitofmeasure', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'SKU (Produit fini)',
                'verbose_name_plural': 'SKUs (Produits finis)',
                'ordering': ['label'],
                'unique_together': {('organization', 'cuvee', 'uom')},
            },
        ),
        migrations.CreateModel(
            name='StockSKUBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_units', models.PositiveIntegerField(default=0, verbose_name='Quantité en unités')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sku', verbose_name='SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Solde stock SKU',
                'verbose_name_plural': 'Soldes stock SKU',
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'sku', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockSKUMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité en unités')),
                ('move_type', models.CharField(choices=[('fabrication', 'Fabrication (embouteillage)'), ('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert'), ('ajustement', 'Ajustement inventaire')], max_length=20, verbose_name='Type de mouvement')),
                ('ref_type', models.CharField(blank=True, max_length=50, verbose_name='Type de référence')),
                ('ref_id', models.UUIDField(blank=True, null=True, verbose_name='ID de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('dst_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_moves_dst', to='viticulture.warehouse', verbose_name='Entrepôt destination')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sku', verbose_name='SKU')),
                ('src_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_moves_src', to='viticulture.warehouse', verbose_name='Entrepôt source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement stock SKU',
                'verbose_name_plural': 'Mouvements stock SKU',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'sku'], name='stock_stock_organiz_8355dc_idx'), models.Index(fields=['organization', 'created_at'], name='stock_stock_organiz_6bed5b_idx'), models.Index(fields=['move_type', 'created_at'], name='stock_stock_move_ty_25c442_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockVracBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_l', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité en litres')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.lot', verbose_name='Lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Solde stock vrac',
                'verbose_name_plural': 'Soldes stock vrac',
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'lot', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockVracMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_l', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité en litres')),
                ('move_type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert'), ('ajustement', 'Ajustement inventaire')], max_length=20, verbose_name='Type de mouvement')),
                ('ref_type', models.CharField(blank=True, help_text="Type d'objet référencé (ex: 'order', 'production')", max_length=50, verbose_name='Type de référence')),
                ('ref_id', models.UUIDField(blank=True, help_text="ID de l'objet référencé", null=True, verbose_name='ID de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('dst_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vrac_moves_dst', to='viticulture.warehouse', verbose_name='Entrepôt destination')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.lot', verbose_name='Lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('src_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vrac_moves_src', to='viticulture.warehouse', verbose_name='Entrepôt source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement stock vrac',
                'verbose_name_plural': 'Mouvements stock vrac',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'lot'], name='stock_stock_organiz_5f963b_idx'), models.Index(fields=['organization', 'created_at'], name='stock_stock_organiz_4ce830_idx'), models.Index(fields=['move_type', 'created_at'], name='stock_stock_move_ty_ab2b90_idx')],
            },
        ),
    ]
