# Generated by Django 5.0.14 on 2025-09-24 07:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('stock', '0001_initial'),
        ('viticulture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume_l', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume transféré (L)')),
                ('client_token', models.CharField(help_text='Token client pour idempotence', max_length=100)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='viticulture.warehouse', verbose_name='Entrepôt source')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.lot', verbose_name='Lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='viticulture.warehouse', verbose_name='Entrepôt destination')),
            ],
            options={
                'verbose_name': 'Transfert stock',
                'verbose_name_plural': 'Transferts stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'client_token'], name='stock_stock_organiz_7d6767_idx'), models.Index(fields=['organization', 'lot', 'created_at'], name='stock_stock_organiz_c2a5bb_idx'), models.Index(fields=['organization', 'created_at'], name='stock_stock_organiz_fe191a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('organization', 'client_token'), name='unique_org_client_token'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(check=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='different_warehouses'),
        ),
    ]
