# Generated by Django 5.0.14 on 2025-09-24 09:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('stock', '0002_stocktransfer_stocktransfer_unique_org_client_token_and_more'),
        ('viticulture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('cuvee', 'Par cuvée'), ('lot', 'Par lot'), ('warehouse', 'Par entrepôt')], max_length=20, verbose_name='Portée du seuil')),
                ('ref_id', models.UUIDField(blank=True, help_text='ID de référence (cuvée, lot, entrepôt) selon scope', null=True)),
                ('threshold_l', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Seuil en litres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Seuil actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Seuil de stock',
                'verbose_name_plural': 'Seuils de stock',
                'ordering': ['scope', 'threshold_l'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_l', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Solde actuel (L)')),
                ('threshold_l', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Seuil appliqué (L)')),
                ('threshold_source', models.CharField(choices=[('global', 'Global'), ('cuvee', 'Par cuvée'), ('lot', 'Par lot'), ('warehouse', 'Par entrepôt')], max_length=20, verbose_name='Source du seuil')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Première détection')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acquittée le')),
                ('auto_resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolue automatiquement le')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acquittée par')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.lot', verbose_name='Lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viticulture.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['organization', 'acknowledged_at', 'first_seen_at'], name='stock_stock_organiz_39d82f_idx'), models.Index(fields=['organization', 'lot', 'warehouse'], name='stock_stock_organiz_92e32a_idx'), models.Index(fields=['organization', 'first_seen_at'], name='stock_stock_organiz_a09c95_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(condition=models.Q(('acknowledged_at__isnull', True), ('auto_resolved_at__isnull', True)), fields=('organization', 'lot', 'warehouse'), name='unique_active_alert_per_lot_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockthreshold',
            index=models.Index(fields=['organization', 'scope', 'is_active'], name='stock_stock_organiz_54fe27_idx'),
        ),
        migrations.AddIndex(
            model_name='stockthreshold',
            index=models.Index(fields=['organization', 'ref_id'], name='stock_stock_organiz_2e6579_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockthreshold',
            constraint=models.UniqueConstraint(fields=('organization', 'scope', 'ref_id'), name='unique_threshold_per_scope_ref'),
        ),
        migrations.AddConstraint(
            model_name='stockthreshold',
            constraint=models.CheckConstraint(check=models.Q(('threshold_l__gt', 0)), name='positive_threshold'),
        ),
    ]
