# Generated by Django 4.2.7 on 2025-10-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('drm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drmline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='drmline',
            index=models.Index(fields=['organization', 'date', 'type'], name='drm_drmline_organiz_34500c_idx'),
        ),
    ]
