# Generated by Django 4.2.7 on 2025-10-22 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0002_drmline_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INAOCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_inao', models.CharField(max_length=32)),
                ('code_nc', models.CharField(max_length=32)),
                ('appellation_label', models.CharField(blank=True, max_length=160)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('condition_text', models.TextField(blank=True)),
                ('packaging_min_l', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('packaging_max_l', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('abv_min_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abv_max_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code_inao', 'code_nc'),
                'indexes': [models.Index(fields=['code_inao'], name='drm_inaocod_code_in_49c33e_idx'), models.Index(fields=['code_nc'], name='drm_inaocod_code_nc_c56f26_idx'), models.Index(fields=['appellation_label', 'color'], name='drm_inaocod_appella_3948a7_idx'), models.Index(fields=['packaging_max_l', 'abv_max_pct'], name='drm_inaocod_packagi_4a50b6_idx')],
            },
        ),
    ]
