# Generated by Django 5.2.8 on 2025-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0003_inaocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drmline',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inaocode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
