# Generated by Django 5.2.8 on 2025-12-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0004_alter_drmline_id_alter_drmline_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inaocode',
            options={'ordering': ('appellation_label', 'code_inao'), 'verbose_name': 'Code INAO', 'verbose_name_plural': 'Codes INAO'},
        ),
        migrations.RemoveIndex(
            model_name='inaocode',
            name='drm_inaocod_appella_3948a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='inaocode',
            name='drm_inaocod_packagi_4a50b6_idx',
        ),
        migrations.AddField(
            model_name='inaocode',
            name='categorie',
            field=models.CharField(blank=True, max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='inaocode',
            name='categorie_code',
            field=models.CharField(choices=[('aop_blanc', 'AOP Blancs'), ('aop_rouge_rose', 'AOP Rouges et Rosés'), ('igp_blanc', 'IGP Blancs'), ('igp_rouge_rose', 'IGP Rouges et Rosés'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='inaocode',
            name='contenance',
            field=models.CharField(blank=True, help_text='Ex: <=2 (litres)', max_length=20, verbose_name='Contenance'),
        ),
        migrations.AddField(
            model_name='inaocode',
            name='date_validite',
            field=models.DateField(blank=True, null=True, verbose_name='Date début validité'),
        ),
        migrations.AddField(
            model_name='inaocode',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Région viticole'),
        ),
        migrations.AddField(
            model_name='inaocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inaocode',
            name='appellation_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Libellé appellation'),
        ),
        migrations.AlterField(
            model_name='inaocode',
            name='code_inao',
            field=models.CharField(max_length=32, verbose_name='Code vinicole interprofessionnel'),
        ),
        migrations.AlterField(
            model_name='inaocode',
            name='code_nc',
            field=models.CharField(max_length=32, verbose_name='Nomenclature combinée (NC)'),
        ),
        migrations.AlterField(
            model_name='inaocode',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='inaocode',
            name='condition_text',
            field=models.TextField(blank=True, verbose_name='Conditions'),
        ),
        migrations.AddIndex(
            model_name='inaocode',
            index=models.Index(fields=['appellation_label'], name='drm_inaocod_appella_edd5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inaocode',
            index=models.Index(fields=['categorie_code', 'region'], name='drm_inaocod_categor_283de4_idx'),
        ),
    ]
