# Generated by Django 5.2.8 on 2025-12-19 23:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID objet')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('spreadsheet', 'Tableur'), ('text', 'Texte'), ('archive', 'Archive'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('contract', 'Contrat'), ('invoice', 'Facture'), ('analysis', 'Analyse'), ('certificate', 'Certificat'), ('photo', 'Photo'), ('report', 'Rapport'), ('regulatory', 'Réglementaire'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'objet")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'content_type', 'object_id'], name='core_docume_organiz_086305_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom technique')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé affiché')),
                ('icon', models.CharField(default='bi-link', max_length=50, verbose_name='Icône Bootstrap')),
                ('related_model', models.CharField(max_length=100, verbose_name='Modèle lié (app.Model)')),
                ('lookup_field', models.CharField(max_length=100, verbose_name='Champ de liaison')),
                ('list_fields', models.JSONField(default=list, verbose_name='Champs à afficher')),
                ('search_fields', models.JSONField(default=list, verbose_name='Champs recherchables')),
                ('default_ordering', models.CharField(default='-created_at', max_length=50, verbose_name='Tri par défaut')),
                ('can_create', models.BooleanField(default=False, verbose_name='Peut créer')),
                ('create_url_name', models.CharField(blank=True, max_length=100, verbose_name='URL de création')),
                ('can_link', models.BooleanField(default=False, verbose_name='Peut lier')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_configs', to='contenttypes.contenttype', verbose_name='Modèle source')),
            ],
            options={
                'verbose_name': 'Configuration relation',
                'verbose_name_plural': 'Configurations relations',
                'ordering': ['source_content_type', 'order'],
                'unique_together': {('source_content_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.CharField(max_length=50, verbose_name='ID objet cible')),
                ('source_object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID objet source')),
                ('event_type', models.CharField(choices=[('operation', 'Opération'), ('document', 'Document'), ('status', 'Changement de statut'), ('note', 'Note'), ('system', 'Système'), ('link', 'Liaison'), ('creation', 'Création'), ('modification', 'Modification'), ('alert', 'Alerte'), ('analysis', 'Analyse'), ('movement', 'Mouvement')], db_index=True, default='system', max_length=20, verbose_name="Type d'événement")),
                ('importance', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Important'), ('critical', 'Critique')], default='normal', max_length=10, verbose_name='Importance')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Données JSON libres pour stocker des infos supplémentaires', verbose_name='Données additionnelles')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Épinglé')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeline_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='accounts.organization', verbose_name='Organisation')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events_as_source', to='contenttypes.contenttype', verbose_name="Type d'objet source")),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events_as_target', to='contenttypes.contenttype', verbose_name="Type d'objet cible")),
            ],
            options={
                'verbose_name': 'Événement timeline',
                'verbose_name_plural': 'Événements timeline',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'target_content_type', 'target_object_id'], name='core_timeli_organiz_7dbbf9_idx'), models.Index(fields=['organization', 'event_type', 'created_at'], name='core_timeli_organiz_d61260_idx'), models.Index(fields=['target_content_type', 'target_object_id', '-created_at'], name='core_timeli_target__8c6ca8_idx')],
            },
        ),
    ]
