# Generated by Django 5.2.8 on 2025-12-13 17:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('clients', '0004_alter_customer_segment'),
        ('produits', '0011_lot_commercial_etiquetage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Numéro')),
                ('reference', models.CharField(blank=True, help_text='Réf client ou fournisseur', max_length=100, verbose_name='Référence externe')),
                ('date_issue', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_due', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('type', models.CharField(choices=[('quote', 'Devis / Proforma'), ('order', 'Commande'), ('delivery', 'Bon de Livraison / Réception'), ('invoice', 'Facture'), ('credit_note', 'Avoir')], db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('sale', 'Vente'), ('purchase', 'Achat')], db_index=True, default='sale', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('validated', 'Validé'), ('executed', 'Exécuté'), ('issued', 'Émis'), ('paid', 'Payé / Soldé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20)),
                ('sale_mode', models.CharField(choices=[('standard', 'Standard'), ('vrac', 'Vrac'), ('primeur', 'Primeur'), ('service', 'Service / Prestation')], default='standard', max_length=20)),
                ('delivery_date_expected', models.DateField(blank=True, null=True, verbose_name='Date livraison prévue')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant réglé')),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_documents', to='clients.customer', verbose_name='Tiers (Client/Fournisseur)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_documents', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='commerce.commercialdocument', verbose_name='Document parent')),
            ],
            options={
                'verbose_name': 'Document commercial',
                'verbose_name_plural': 'Documents commerciaux',
                'ordering': ['-date_issue', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Prix unitaire')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise %')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Taux TVA')),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.commercialdocument')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_lines', to='produits.sku')),
            ],
            options={
                'verbose_name': 'Ligne commerciale',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('virement', 'Virement'), ('cb', 'Carte Bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('prelevement', 'Prélèvement'), ('autre', 'Autre')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Numéro chèque, virement...', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='commerce.commercialdocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_payments', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialdocument',
            index=models.Index(fields=['organization', 'type', 'status'], name='commerce_co_organiz_37e996_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialdocument',
            index=models.Index(fields=['organization', 'client'], name='commerce_co_organiz_7f6d99_idx'),
        ),
    ]
