# Generated by Django 4.2.7 on 2025-11-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_dashboardwidget_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('skipped', models.JSONField(blank=True, default=dict)),
                ('last_step_completed', models.CharField(blank=True, max_length=32)),
                ('dismissed', models.BooleanField(default=False, help_text='Onboarding masqué pour cette organisation')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Onboarding – État',
                'verbose_name_plural': 'Onboarding – États',
                'indexes': [models.Index(fields=['organization'], name='onboarding__organiz_086b05_idx')],
            },
        ),
    ]
