# Generated by Django 5.0.14 on 2025-09-21 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50, verbose_name='Numéro de lot')),
                ('millesime', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Millésime')),
                ('volume_initial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume initial')),
                ('volume_actuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume actuel')),
                ('degre_alcool', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Degré d'alcool (%)")),
                ('densite', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(1.2)], verbose_name='Densité')),
                ('statut', models.CharField(choices=[('production', 'En production'), ('fermentation', 'En fermentation'), ('elevage', 'En élevage'), ('assemblage', 'En assemblage'), ('conditionnement', 'En conditionnement'), ('stock', 'En stock'), ('vendu', 'Vendu'), ('perdu', 'Perdu/Détruit')], default='production', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateField(verbose_name='Date de création du lot')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuvee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='referentiels.cuvee')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='referentiels.entrepot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounts.organization')),
                ('unite_volume', models.ForeignKey(limit_choices_to={'type_unite': 'volume'}, on_delete=django.db.models.deletion.PROTECT, related_name='lots_volume', to='referentiels.unite', verbose_name='Unité de volume')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-millesime', 'numero_lot'],
                'unique_together': {('organization', 'numero_lot', 'millesime')},
            },
        ),
        migrations.CreateModel(
            name='MouvementLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('creation', 'Création du lot'), ('transfert_entrepot', "Transfert d'entrepôt"), ('assemblage', 'Assemblage'), ('soutirage', 'Soutirage'), ('filtration', 'Filtration'), ('conditionnement', 'Conditionnement'), ('vente', 'Vente'), ('perte', 'Perte/Casse'), ('correction', 'Correction manuelle'), ('autre', 'Autre')], max_length=20, verbose_name='Type de mouvement')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('volume_avant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume avant')),
                ('volume_mouvement', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume du mouvement')),
                ('volume_apres', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume après')),
                ('date_mouvement', models.DateTimeField(verbose_name='Date du mouvement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepot_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_entree', to='referentiels.entrepot', verbose_name='Entrepôt destination')),
                ('entrepot_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_sortie', to='referentiels.entrepot', verbose_name='Entrepôt source')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='catalogue.lot')),
            ],
            options={
                'verbose_name': 'Mouvement de lot',
                'verbose_name_plural': 'Mouvements de lots',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
