# Generated by Django 5.2.8 on 2025-12-13 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('catalogue', '0001_initial'),
        ('referentiels', '0012_cepage_couleur_libre_alter_cepage_couleur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='accounts.organization')),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'articles",
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('product', 'Produit stockable'), ('traceable', 'Produit traçable (Vin/Lot)'), ('service', 'Service / Prestation'), ('stay', 'Nuitée / Hébergement'), ('pack', 'Pack / Bundle')], default='product', max_length=20, verbose_name="Type d'article")),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('sku', models.CharField(blank=True, help_text='Référence unique interne', max_length=50, verbose_name='Code article (SKU)')),
                ('description', models.TextField(blank=True, help_text='Pour devis/factures', verbose_name='Description courte')),
                ('price_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('unit', models.CharField(default='PCE', help_text='PCE, L, KG, NUIT, PERS...', max_length=20, verbose_name='Unité de vente')),
                ('is_stock_managed', models.BooleanField(default=True, help_text='Si actif, le système suit les quantités.', verbose_name='Gestion de stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.organization')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalogue.articlecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['category', 'name'],
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjust', 'Ajustement')], max_length=10, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positif pour entrée, Négatif pour sortie (géré par logique métier)', max_digits=12, verbose_name='Quantité')),
                ('batch_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Lot/Batch')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('reference', models.CharField(blank=True, help_text='Ex: Facture #123, Prod #456', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalogue.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='referentiels.entrepot', verbose_name='Emplacement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, default='', help_text='Vide pour produits non traçables', max_length=50, verbose_name='Numéro de lot/batch')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité en stock')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lines', to='catalogue.article')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_stocks', to='referentiels.entrepot', verbose_name='Emplacement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Ligne de stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['article', 'batch_number'],
                'unique_together': {('article', 'location', 'batch_number')},
            },
        ),
    ]
