# Generated by Django 5.2.8 on 2025-12-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_articlecategory_article_stockmovement_articlestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_buyable',
            field=models.BooleanField(default=True, help_text='Peut être acheté (Fournisseurs)', verbose_name='Achetable'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_sellable',
            field=models.BooleanField(default=True, help_text='Peut être vendu (Clients)', verbose_name='Vendable'),
        ),
    ]
