# Generated by Django 5.2.8 on 2025-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_article_is_buyable_article_is_sellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat de référence (PA HT)", max_digits=10, verbose_name="Prix d'achat HT"),
        ),
    ]
