# Generated by Django 5.2.8 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_article_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo produit'),
        ),
        migrations.AddField(
            model_name='article',
            name='tasting_notes',
            field=models.TextField(blank=True, help_text='Fiche de dégustation, arômes, accords mets-vins...', verbose_name='Notes de dégustation'),
        ),
    ]
