# Generated by Django 5.2.8 on 2025-12-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('catalogue', '0005_article_image_article_tasting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alcohol_degree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="Degré d'alcool (%)"),
        ),
        migrations.AddField(
            model_name='article',
            name='customs_notes',
            field=models.TextField(blank=True, verbose_name='Notes douanières'),
        ),
        migrations.AddField(
            model_name='article',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Code nomenclature pour export', max_length=20, verbose_name='Code Douanier (HS)'),
        ),
        migrations.AddField(
            model_name='article',
            name='net_volume',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Volume en litres pour la régie', max_digits=10, null=True, verbose_name='Volume net (L)'),
        ),
        migrations.AddField(
            model_name='article',
            name='origin_country',
            field=models.CharField(blank=True, default='France', max_length=100, verbose_name="Pays d'origine"),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Tag produit',
                'verbose_name_plural': 'Tags produits',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='catalogue.articletag', verbose_name='Tags'),
        ),
    ]
