# Generated by Django 5.2.8 on 2026-01-13 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_article_alcohol_degree_article_customs_notes_and_more'),
        ('produits', '0015_alter_purchasebatchbottle_supplier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='articlestock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lines', to='produits.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='produits.product'),
        ),
    ]
