# Generated by Django 5.2.8 on 2026-01-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_article_unique_together_and_more'),
        ('sales', '0009_alter_priceitem_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
