# Generated by Django 5.0.14 on 2025-09-21 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('name', models.CharField(help_text="Nom de l'appellation", max_length=200)),
                ('name_norm', models.CharField(editable=False, help_text='Nom normalisé pour unicité', max_length=200)),
                ('type', models.CharField(choices=[('aoc', 'AOC'), ('igp', 'IGP'), ('vsig', 'VSIG'), ('autre', 'Autre')], help_text="Type d'appellation", max_length=10)),
                ('region', models.CharField(blank=True, help_text='Région viticole', max_length=100)),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Appellation',
                'verbose_name_plural': 'Appellations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cuvee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('name', models.CharField(help_text='Nom de la cuvée', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Code produit (optionnel)', max_length=50)),
                ('appellation', models.ForeignKey(blank=True, help_text='Appellation de la cuvée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='viticulture.appellation')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Cuvée',
                'verbose_name_plural': 'Cuvées',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('name', models.CharField(help_text='Nom du cépage', max_length=100)),
                ('name_norm', models.CharField(editable=False, help_text='Nom normalisé pour unicité', max_length=100)),
                ('color', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé')], help_text='Couleur du raisin', max_length=10)),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Cépage',
                'verbose_name_plural': 'Cépages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('code', models.CharField(help_text='Code unique du lot', max_length=50)),
                ('volume_l', models.DecimalField(decimal_places=2, help_text='Volume en litres', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('alcohol_pct', models.DecimalField(blank=True, decimal_places=2, help_text="Degré d'alcool (%)", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('elevage', 'Élevage'), ('stabilise', 'Stabilisé'), ('embouteille', 'Embouteillé'), ('archive', 'Archivé')], default='en_cours', help_text='Statut du lot', max_length=15)),
                ('cuvee', models.ForeignKey(help_text='Cuvée du lot', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='viticulture.cuvee')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Lot de production',
                'verbose_name_plural': 'Lots de production',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotAssemblage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_l', models.DecimalField(decimal_places=2, help_text='Volume assemblé en litres', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_lot', models.ForeignKey(help_text="Lot source de l'assemblage", on_delete=django.db.models.deletion.CASCADE, related_name='assemblages_as_child', to='viticulture.lot')),
                ('parent_lot', models.ForeignKey(help_text="Lot résultant de l'assemblage", on_delete=django.db.models.deletion.CASCADE, related_name='assemblages_as_parent', to='viticulture.lot')),
            ],
            options={
                'verbose_name': 'Assemblage de lots',
                'verbose_name_plural': 'Assemblages de lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotGrapeRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_pct', models.DecimalField(decimal_places=2, help_text='Pourcentage du cépage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('grape_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viticulture.grapevariety')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grape_ratios', to='viticulture.lot')),
            ],
            options={
                'verbose_name': 'Composition cépage',
                'verbose_name_plural': 'Compositions cépages',
                'ordering': ['-ratio_pct'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('code', models.CharField(help_text='Code court (L, hL, BT)', max_length=10)),
                ('name', models.CharField(help_text='Nom complet', max_length=50)),
                ('base_ratio_to_l', models.DecimalField(decimal_places=6, help_text='Ratio de conversion vers litres (1 hL = 100 L)', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text="Unité par défaut pour l'organisation")),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cuvee',
            name='default_uom',
            field=models.ForeignKey(help_text='Unité de mesure par défaut', on_delete=django.db.models.deletion.PROTECT, to='viticulture.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='VineyardPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('name', models.CharField(help_text='Nom de la parcelle', max_length=100)),
                ('area_ha', models.DecimalField(decimal_places=4, help_text='Surface en hectares', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('planting_year', models.PositiveIntegerField(blank=True, help_text='Année de plantation', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('appellation', models.ForeignKey(blank=True, help_text='Appellation de la parcelle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='viticulture.appellation')),
                ('grape_variety', models.ForeignKey(help_text='Cépage principal planté', on_delete=django.db.models.deletion.PROTECT, to='viticulture.grapevariety')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Parcelle de vignes',
                'verbose_name_plural': 'Parcelles de vignes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('year', models.PositiveIntegerField(help_text='Année du millésime', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Millésime',
                'verbose_name_plural': 'Millésimes',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='cuvee',
            name='vintage',
            field=models.ForeignKey(blank=True, help_text='Millésime de la cuvée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='viticulture.vintage'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('name', models.CharField(help_text="Nom de l'entrepôt", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Localisation/adresse', max_length=200)),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='warehouse',
            field=models.ForeignKey(help_text='Entrepôt de stockage', on_delete=django.db.models.deletion.PROTECT, to='viticulture.warehouse'),
        ),
        migrations.AddIndex(
            model_name='appellation',
            index=models.Index(fields=['organization', 'name_norm'], name='viticulture_organiz_e10da9_idx'),
        ),
        migrations.AddIndex(
            model_name='appellation',
            index=models.Index(fields=['organization', 'type'], name='viticulture_organiz_a95adb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appellation',
            unique_together={('organization', 'name_norm')},
        ),
        migrations.AddIndex(
            model_name='grapevariety',
            index=models.Index(fields=['organization', 'name_norm'], name='viticulture_organiz_fa9650_idx'),
        ),
        migrations.AddIndex(
            model_name='grapevariety',
            index=models.Index(fields=['organization', 'color'], name='viticulture_organiz_eda02b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grapevariety',
            unique_together={('organization', 'name_norm')},
        ),
        migrations.AlterUniqueTogether(
            name='lotassemblage',
            unique_together={('parent_lot', 'child_lot', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='lotgraperatio',
            unique_together={('lot', 'grape_variety')},
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['organization', 'code'], name='viticulture_organiz_6022e7_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['organization', 'is_default'], name='viticulture_organiz_03bf3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='vineyardplot',
            index=models.Index(fields=['organization', 'name'], name='viticulture_organiz_7666f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vineyardplot',
            index=models.Index(fields=['organization', 'grape_variety'], name='viticulture_organiz_bacec6_idx'),
        ),
        migrations.AddIndex(
            model_name='vineyardplot',
            index=models.Index(fields=['organization', 'appellation'], name='viticulture_organiz_8f0a30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vineyardplot',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='vintage',
            index=models.Index(fields=['organization', 'year'], name='viticulture_organiz_9c593e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vintage',
            unique_together={('organization', 'year')},
        ),
        migrations.AddIndex(
            model_name='cuvee',
            index=models.Index(fields=['organization', 'name'], name='viticulture_organiz_ccd1de_idx'),
        ),
        migrations.AddIndex(
            model_name='cuvee',
            index=models.Index(fields=['organization', 'vintage'], name='viticulture_organiz_b3a861_idx'),
        ),
        migrations.AddIndex(
            model_name='cuvee',
            index=models.Index(fields=['organization', 'appellation'], name='viticulture_organiz_c6f345_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cuvee',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['organization', 'code'], name='viticulture_organiz_3b05fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['organization', 'cuvee'], name='viticulture_organiz_5cd252_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['organization', 'status'], name='viticulture_organiz_f52221_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['organization', 'warehouse'], name='viticulture_organiz_27fbf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('organization', 'code')},
        ),
    ]
