# Generated by Django 5.0.14 on 2025-09-27 05:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('viticulture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuveeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('type_vin', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé'), ('petillant', 'Pétillant'), ('doux', 'Doux'), ('sec', 'Sec'), ('moelleux', 'Moelleux'), ('liquoreux', 'Liquoreux')], default='rouge', help_text='Type de vin', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('fini', 'Fini'), ('vendu', 'Vendu'), ('archive', 'Archivé')], default='en_cours', help_text='Statut de la cuvée', max_length=20)),
                ('numero_interne', models.UUIDField(default=uuid.uuid4, help_text='Numéro interne unique', unique=True)),
                ('volume_total_hl', models.DecimalField(blank=True, decimal_places=2, help_text='Volume total vinifié (HL)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_vendange_debut', models.DateField(blank=True, help_text='Date de début des vendanges', null=True)),
                ('date_vendange_fin', models.DateField(blank=True, help_text='Date de fin des vendanges', null=True)),
                ('methode_vendange', models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('mecanique', 'Mécanique'), ('mixte', 'Mixte')], help_text='Méthode de vendange', max_length=20)),
                ('methode_vinification', models.CharField(blank=True, choices=[('cuve_inox', 'Cuve inox'), ('cuve_beton', 'Cuve béton'), ('fut_chene', 'Fût chêne'), ('amphore', 'Amphore'), ('maceration_carbonique', 'Macération carbonique'), ('autre', 'Autre')], help_text='Méthode de vinification', max_length=30)),
                ('duree_elevage_mois', models.PositiveIntegerField(blank=True, help_text="Durée d'élevage en mois", null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('contenant_elevage', models.CharField(blank=True, choices=[('cuve', 'Cuve'), ('fut_neuf', 'Fût neuf'), ('fut_ancien', 'Fût ancien'), ('barrique', 'Barrique'), ('demi_muid', 'Demi-muid'), ('autre', 'Autre')], help_text="Contenant d'élevage", max_length=20)),
                ('degre_alcool_potentiel', models.DecimalField(blank=True, decimal_places=2, help_text='Degré alcool potentiel (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('degre_alcool_final', models.DecimalField(blank=True, decimal_places=2, help_text='Degré alcool final (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('sucres_residuels', models.DecimalField(blank=True, decimal_places=2, help_text='Sucres résiduels (g/L)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ph', models.DecimalField(blank=True, decimal_places=2, help_text='pH', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('2.5')), django.core.validators.MaxValueValidator(Decimal('4.5'))])),
                ('acidite_totale', models.DecimalField(blank=True, decimal_places=2, help_text='Acidité totale (g/L H2SO4)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('so2_libre', models.DecimalField(blank=True, decimal_places=2, help_text='SO2 libre (mg/L)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('so2_total', models.DecimalField(blank=True, decimal_places=2, help_text='SO2 total (mg/L)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('prix_revient_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de revient estimé (€/L)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('certifications', models.CharField(blank=True, help_text='Certifications (séparées par des virgules)', max_length=100)),
                ('notes_internes', models.TextField(blank=True, help_text="Notes internes pour l'équipe")),
                ('notes_degustation', models.TextField(blank=True, help_text='Notes de dégustation')),
                ('cuvee', models.OneToOneField(help_text='Cuvée de référence', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='viticulture.cuvee')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Détail de cuvée',
                'verbose_name_plural': 'Détails de cuvées',
                'ordering': ['-created_at'],
            },
        ),
    ]
