# Generated by Django 5.0.14 on 2025-09-27 07:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viticulture', '0002_cuveedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuveedetail',
            name='etiquette_image',
            field=models.ImageField(blank=True, help_text="Image de l'étiquette", null=True, upload_to='cuvees/etiquettes/'),
        ),
        migrations.CreateModel(
            name='CuveeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analyse', models.DateField(default=django.utils.timezone.now, help_text="Date de l'analyse")),
                ('type_analyse', models.CharField(help_text="Type d'analyse", max_length=50)),
                ('resultats', models.JSONField(help_text="Résultats de l'analyse (JSON)")),
                ('laboratoire', models.CharField(blank=True, help_text="Laboratoire d'analyse", max_length=100)),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'analyse")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuvee_detail', models.ForeignKey(help_text='Détail de la cuvée', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='viticulture.cuveedetail')),
            ],
            options={
                'verbose_name': 'Analyse de cuvée',
                'verbose_name_plural': 'Analyses de cuvées',
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='CuveeParcelleRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, help_text='Pourcentage de la parcelle (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('cuvee_detail', models.ForeignKey(help_text='Détail de la cuvée', on_delete=django.db.models.deletion.CASCADE, to='viticulture.cuveedetail')),
                ('parcelle', models.ForeignKey(help_text='Parcelle', on_delete=django.db.models.deletion.CASCADE, to='viticulture.vineyardplot')),
            ],
            options={
                'verbose_name': 'Ratio parcelle',
                'verbose_name_plural': 'Ratios parcelles',
                'unique_together': {('cuvee_detail', 'parcelle')},
            },
        ),
        migrations.AddField(
            model_name='cuveedetail',
            name='parcelles',
            field=models.ManyToManyField(help_text='Parcelles utilisées', through='viticulture.CuveeParcelleRatio', to='viticulture.vineyardplot'),
        ),
        migrations.CreateModel(
            name='CuveeCepageRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, help_text='Pourcentage du cépage (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('cepage', models.ForeignKey(help_text='Cépage', on_delete=django.db.models.deletion.CASCADE, to='viticulture.grapevariety')),
                ('cuvee_detail', models.ForeignKey(help_text='Détail de la cuvée', on_delete=django.db.models.deletion.CASCADE, related_name='cepages_ratios', to='viticulture.cuveedetail')),
            ],
            options={
                'verbose_name': 'Ratio cépage',
                'verbose_name_plural': 'Ratios cépages',
                'unique_together': {('cuvee_detail', 'cepage')},
            },
        ),
    ]
