# Generated by Django 5.0.14 on 2025-09-27 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('viticulture', '0003_cuveedetail_etiquette_image_cuveeanalyse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('type', models.CharField(choices=[('cuve', 'Cuve'), ('fut', 'Fût'), ('barrique', 'Barrique'), ('autre', 'Autre')], max_length=20)),
                ('capacite_l', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_occupe_l', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identifiant', models.CharField(blank=True, max_length=50)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenants', to='viticulture.lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Contenant de lot',
                'verbose_name_plural': 'Contenants de lot',
                'ordering': ['type', 'identifiant'],
            },
        ),
        migrations.CreateModel(
            name='LotDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('emplacement_rangee', models.CharField(blank=True, max_length=50)),
                ('emplacement_travee', models.CharField(blank=True, max_length=50)),
                ('emplacement_niveau', models.CharField(blank=True, max_length=50)),
                ('temperature_cible_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ouillage_requis', models.BooleanField(default=False)),
                ('ouillage_periodicite_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('ouillage_dernier_controle', models.DateField(blank=True, null=True)),
                ('volume_brut_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume_net_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('titre_alcoolique_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sr_g_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('at_g_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('so2_libre_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('so2_total_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('etat_microbio', models.CharField(blank=True, choices=[('ok', 'OK'), ('surveillance', 'Surveillance'), ('action', 'Action requise')], max_length=20)),
                ('clarification_technique', models.CharField(blank=True, help_text='Collage/Filtration/Autre', max_length=50)),
                ('clarification_details', models.TextField(blank=True)),
                ('elevage_type', models.CharField(blank=True, max_length=50)),
                ('elevage_duree_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('cout_matieres_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_main_oeuvre_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_unitaire_eur_l', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valorisation_methode', models.CharField(choices=[('cmp', 'Coût moyen pondéré (CMP)'), ('fifo', 'FIFO')], default='cmp', max_length=10)),
                ('destinations', models.CharField(blank=True, help_text='Destinations (CSV)', max_length=100)),
                ('drm_categorie', models.CharField(blank=True, max_length=50)),
                ('certifications', models.CharField(blank=True, help_text='Certifications sur ce lot', max_length=100)),
                ('etiquetage_mentions', models.TextField(blank=True)),
                ('etiquetage_allergenes', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('lot', models.OneToOneField(help_text='Lot de référence', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='viticulture.lot')),
                ('millesime_majoritaire', models.ForeignKey(blank=True, help_text='Millésime majoritaire du lot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='viticulture.vintage')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Détail de lot',
                'verbose_name_plural': 'Détails de lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('document', models.FileField(upload_to='lots/documents/')),
                ('type', models.CharField(choices=[('analyse_labo', 'Analyse labo'), ('cip', 'CIP'), ('photo', 'Photo'), ('pdf', 'PDF'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='viticulture.lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Document de lot',
                'verbose_name_plural': 'Documents de lot',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LotIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('type', models.CharField(choices=[('chaptalisation', 'Chaptalisation'), ('acidification', 'Acidification'), ('so2', 'Ajout SO₂'), ('batonnage', 'Bâtonnage'), ('soutirage', 'Soutirage'), ('fml', 'Fermentation malolactique'), ('filtration', 'Filtration'), ('collage', 'Collage'), ('correction', 'Correction autre')], max_length=30)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('volume_in_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume_out_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('drm_code', models.CharField(blank=True, max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='viticulture.lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Intervention de lot',
                'verbose_name_plural': 'Interventions de lot',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LotSourceCuvee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuvee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viticulture.cuvee')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_cuvees', to='viticulture.lot')),
            ],
            options={
                'verbose_name': 'Source cuvée',
                'verbose_name_plural': 'Sources cuvées',
                'unique_together': {('lot', 'cuvee')},
            },
        ),
        migrations.CreateModel(
            name='LotSourceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_lots', to='viticulture.lot')),
                ('source_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_comme_source', to='viticulture.lot')),
            ],
            options={
                'verbose_name': 'Source lot',
                'verbose_name_plural': 'Sources lots',
                'unique_together': {('lot', 'source_lot')},
            },
        ),
    ]
