# Generated by Django 5.0.14 on 2025-09-29 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('viticulture', '0004_lotcontainer_lotdetail_lotdocument_lotintervention_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuvee',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CuveeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('name', models.CharField(help_text='Nom du modèle de cuvée', max_length=120)),
                ('code', models.CharField(blank=True, help_text='Code interne (optionnel)', max_length=40)),
                ('recette', models.JSONField(blank=True, default=dict, help_text='Règles recette: cépages attendus, élevage cible, mentions')),
                ('style', models.CharField(blank=True, help_text='Style (rouge/blanc/rosé/…)', max_length=20)),
                ('appellation_target', models.ForeignKey(blank=True, help_text='Appellation visée (INAO)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='viticulture.appellation')),
                ('default_uom', models.ForeignKey(help_text='Unité de mesure par défaut', on_delete=django.db.models.deletion.PROTECT, to='viticulture.unitofmeasure')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Modèle de cuvée',
                'verbose_name_plural': 'Modèles de cuvées',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cuvee',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Modèle de cuvée (identité pérenne)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vintages', to='viticulture.cuveemodel'),
        ),
        migrations.AddConstraint(
            model_name='cuvee',
            constraint=models.UniqueConstraint(condition=models.Q(('model__isnull', False), ('vintage__isnull', False)), fields=('organization', 'model', 'vintage'), name='uniq_org_model_vintage_not_null'),
        ),
        migrations.AddIndex(
            model_name='cuveemodel',
            index=models.Index(fields=['organization', 'name'], name='viticulture_organiz_7a2122_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuveemodel',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'appellation_target'), name='uniq_cuveemodel_org_name_appellation'),
        ),
    ]
