# Generated by Django 4.2.7 on 2025-10-02 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        ('viticulture', '0005_alter_cuvee_unique_together_cuveemodel_cuvee_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotintervention',
            name='type',
            field=models.CharField(choices=[('chaptalisation', 'Chaptalisation'), ('acidification', 'Acidification'), ('so2', 'Ajout SO₂'), ('batonnage', 'Bâtonnage'), ('soutirage', 'Soutirage'), ('fml', 'Fermentation malolactique'), ('filtration', 'Filtration'), ('collage', 'Collage'), ('correction', 'Correction autre'), ('remontage', 'Remontage'), ('pigeage', 'Pigeage'), ('ouillage', 'Ouillage'), ('pressurage', 'Pressurage/Écoulage')], max_length=30),
        ),
        migrations.CreateModel(
            name='LotMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('type', models.CharField(choices=[('temperature', 'Température (°C)'), ('densite', 'Densité'), ('sucre', 'Sucres (g/L)'), ('ph', 'pH')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='viticulture.lot')),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Mesure de lot',
                'verbose_name_plural': 'Mesures de lot',
                'ordering': ['-date'],
            },
        ),
    ]
