# Generated by Django 4.2.7 on 2025-10-21 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0007_importbatch_parcelle_cepages_importexecution'),
        ('accounts', '0010_create_default_orgsettings'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('viticulture', '0007_parcelleoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelleJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('surface_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rangs', models.CharField(blank=True, max_length=120)),
                ('resume', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('cout_mo_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_matiere_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_total_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelleOperationType',
            fields=[
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.DeleteModel(
            name='ParcelleOperation',
        ),
        migrations.AddField(
            model_name='parcellejournalentry',
            name='op_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viticulture.parcelleoperationtype'),
        ),
        migrations.AddField(
            model_name='parcellejournalentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='parcellejournalentry',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='referentiels.parcelle'),
        ),
        migrations.AddField(
            model_name='parcellejournalentry',
            name='source_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='parcellejournalentry',
            index=models.Index(fields=['organization', 'parcelle', 'date'], name='viticulture_organiz_1879ff_idx'),
        ),
        migrations.AddIndex(
            model_name='parcellejournalentry',
            index=models.Index(fields=['organization', 'op_type'], name='viticulture_organiz_0fff0f_idx'),
        ),
    ]
