# Generated by Django 5.2.8 on 2025-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viticulture', '0008_parcellejournalentry_parcelleoperationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotintervention',
            name='type',
            field=models.CharField(choices=[('chaptalisation', 'Chaptalisation'), ('acidification', 'Acidification'), ('so2', 'Ajout SO₂'), ('batonnage', 'Bâtonnage'), ('soutirage', 'Soutirage'), ('fml', 'Fermentation malolactique'), ('filtration', 'Filtration'), ('collage', 'Collage'), ('correction', 'Correction autre'), ('remontage', 'Remontage'), ('pigeage', 'Pigeage'), ('ouillage', 'Ouillage'), ('pressurage', 'Pressurage/Écoulage'), ('debourbage', 'Débourbage'), ('inoculation_levures', 'Inoculation levures'), ('inoculation_bacteries', 'Inoculation bactéries'), ('delestage', 'Délestage'), ('debut_fa', 'Début FA'), ('fin_fa', 'Fin FA'), ('debut_fml', 'Début FML'), ('fin_fml', 'Fin FML')], max_length=30),
        ),
    ]
