# Generated by Django 5.2.8 on 2025-11-26 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_fix_dashboard_config_fk'),
        ('referentiels', '0007_importbatch_parcelle_cepages_importexecution'),
        ('viticulture', '0009_add_parcelle_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelleOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1, help_text='Version pour locking optimiste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete')),
                ('operation_type', models.CharField(choices=[('taille', 'Taille'), ('traitement', 'Traitement phyto'), ('palissage', 'Palissage / Liage'), ('rognage', 'Rognage'), ('effeuillage', 'Effeuillage'), ('travail_sol', 'Travail du sol'), ('fertilisation', 'Fertilisation / Amendements'), ('irrigation', 'Irrigation'), ('observation', 'Observation'), ('vendange', 'Vendange'), ('autre', 'Autre')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('label', models.CharField(blank=True, help_text='Intitulé court', max_length=120)),
                ('produit', models.CharField(blank=True, help_text='Produit utilisé (si traitement)', max_length=120)),
                ('dose', models.CharField(blank=True, help_text='Dose/ha ou quantité', max_length=60)),
                ('duree_h', models.DecimalField(blank=True, decimal_places=2, help_text='Durée (heures)', max_digits=6, null=True)),
                ('cout_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Coût (€)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(help_text='Organisation propriétaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('parcelle', models.ForeignKey(help_text='Parcelle concernée', on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='referentiels.parcelle')),
            ],
            options={
                'verbose_name': 'Opération de parcelle',
                'verbose_name_plural': 'Opérations de parcelle',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'parcelle', 'date'], name='viticulture_organiz_b69b94_idx'), models.Index(fields=['organization', 'operation_type', 'date'], name='viticulture_organiz_e9021a_idx')],
            },
        ),
    ]
