# Generated by Django 5.2.8 on 2026-01-08 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viticulture', '0011_alter_appellation_id_alter_cuvee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyardplot',
            name='planting_year',
            field=models.PositiveIntegerField(blank=True, help_text='Année de plantation', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='vintage',
            name='year',
            field=models.PositiveIntegerField(help_text='Année du millésime', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
