# Generated by Django 5.0.14 on 2025-09-24 11:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('segment', models.CharField(choices=[('individual', 'Particulier'), ('business', 'Professionnel'), ('wine_shop', 'Caviste'), ('export', 'Export'), ('other', 'Autre')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_norm', models.CharField(help_text='Nom normalisé pour recherche', max_length=255)),
                ('vat_number', models.CharField(blank=True, help_text='Numéro de TVA (requis pour business/export)', max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Code pays ISO 3166-1 alpha-2')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'clients_customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('activity_type', models.CharField(choices=[('contact', 'Contact'), ('quote', 'Devis'), ('order', 'Commande'), ('invoice', 'Facture'), ('payment', 'Paiement'), ('visit', 'Visite'), ('email', 'Email'), ('call', 'Appel'), ('note', 'Note')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('ref_type', models.CharField(blank=True, help_text="Type d'objet référencé", max_length=50)),
                ('ref_id', models.UUIDField(blank=True, help_text="ID de l'objet référencé", null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'clients_customer_activity',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6c757d', help_text="Couleur hexadécimale pour l'affichage", max_length=7)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'clients_customer_tag',
            },
        ),
        migrations.CreateModel(
            name='CustomerTagLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='clients.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_%(class)s_set', to='accounts.organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='clients.customertag')),
            ],
            options={
                'db_table': 'clients_customer_tag_link',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_norm'], name='clients_cust_name_norm_gin'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='clients_cust_search_gin'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'segment'], name='clients_cust_org_segment_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'is_active'], name='clients_cust_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='clients_cust_keyset_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number__isnull', False)), fields=('organization', 'vat_number'), name='unique_customer_vat_per_org'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'name_norm'), name='unique_customer_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['customer', 'activity_date'], name='clients_act_cust_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['organization', 'activity_type'], name='clients_act_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['ref_type', 'ref_id'], name='clients_act_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['organization', 'name'], name='clients_tag_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='customertag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_customer_tag_per_org'),
        ),
        migrations.AddIndex(
            model_name='customertaglink',
            index=models.Index(fields=['customer'], name='clients_tag_link_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='customertaglink',
            index=models.Index(fields=['tag'], name='clients_tag_link_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='customertaglink',
            constraint=models.UniqueConstraint(fields=('organization', 'customer', 'tag'), name='unique_customer_tag_link'),
        ),
    ]
