# Generated by Django 5.0.14 on 2025-09-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_create_clients_models'),
    ]

    operations = [
    ]
