# Generated by Django 5.0.14 on 2025-09-24 19:30

import apps.clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_validator_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country_code',
            field=models.CharField(blank=True, help_text='Code pays ISO 3166-1 alpha-2 (FR, DE, IT...)', max_length=2, null=True, validators=[apps.clients.validators.CountryCodeValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email (normalisée automatiquement)', max_length=254, null=True, validators=[apps.clients.validators.AdvancedEmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Nom du client (2-120 caractères)', max_length=120, validators=[apps.clients.validators.CustomerNameValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_norm',
            field=models.CharField(help_text='Nom normalisé pour recherche (généré automatiquement)', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Téléphone au format E.164 (+33123456789)', max_length=20, null=True, validators=[apps.clients.validators.PhoneE164Validator(country_code=None)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire (requis pour business/export)', max_length=15, null=True, validators=[apps.clients.validators.VATNumberValidator(country_code=None)]),
        ),
    ]
