# Generated by Django 5.2.8 on 2025-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_customer_country_code_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[('individual', 'Particulier'), ('business', 'Professionnel'), ('wine_shop', 'Caviste'), ('export', 'Export'), ('supplier', 'Fournisseur'), ('other', 'Autre')], max_length=20),
        ),
    ]
