# Generated by Django 5.0.14 on 2025-09-21 07:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du cépage')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code (optionnel)')),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé')], default='rouge', max_length=10, verbose_name='Couleur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cepages', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Cépage',
                'verbose_name_plural': 'Cépages',
                'ordering': ['nom'],
                'unique_together': {('organization', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Cuvee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la cuvée')),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé'), ('effervescent', 'Effervescent')], max_length=15, verbose_name='Couleur')),
                ('classification', models.CharField(choices=[('aoc', 'AOC'), ('igp', 'IGP'), ('vsig', 'VSIG'), ('vdf', 'Vin de France')], max_length=20, verbose_name='Classification')),
                ('appellation', models.CharField(blank=True, max_length=100, verbose_name='Appellation')),
                ('degre_alcool', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Degré d'alcool (%)")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes_degustation', models.TextField(blank=True, verbose_name='Notes de dégustation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cepages', models.ManyToManyField(blank=True, to='referentiels.cepage', verbose_name='Cépages')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuvees', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Cuvée',
                'verbose_name_plural': 'Cuvées',
                'ordering': ['nom'],
                'unique_together': {('organization', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'entrepôt")),
                ('type_entrepot', models.CharField(choices=[('chai', 'Chai'), ('depot', 'Dépôt'), ('boutique', 'Boutique'), ('cave', 'Cave'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'entrepôt")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('capacite', models.PositiveIntegerField(blank=True, help_text='Capacité en nombre de bouteilles', null=True, verbose_name='Capacité')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température min (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température max (°C)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['type_entrepot', 'nom'],
                'unique_together': {('organization', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la parcelle')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Surface (hectares)')),
                ('lieu_dit', models.CharField(blank=True, max_length=200, verbose_name='Lieu-dit')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('appellation', models.CharField(blank=True, max_length=100, verbose_name='Appellation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['nom'],
                'unique_together': {('organization', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'unité")),
                ('symbole', models.CharField(max_length=10, verbose_name='Symbole')),
                ('type_unite', models.CharField(choices=[('volume', 'Volume'), ('poids', 'Poids'), ('surface', 'Surface'), ('quantite', 'Quantité')], default='volume', max_length=20, verbose_name="Type d'unité")),
                ('facteur_conversion', models.DecimalField(decimal_places=4, default=1.0, help_text="Facteur de conversion vers l'unité de base (ex: 1 bouteille = 0.75 L)", max_digits=10, verbose_name='Facteur de conversion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['type_unite', 'nom'],
                'unique_together': {('organization', 'nom')},
            },
        ),
    ]
