# Generated by Django 5.0.14 on 2025-09-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0003_cepage_roadmap19'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cepage',
            new_name='referentiel_organiz_49d2b6_idx',
            old_name='referentiels_cepage_org_name_norm_idx',
        ),
    ]
