# Generated by Django 4.2.7 on 2025-10-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0004_rename_referentiels_cepage_org_name_norm_idx_referentiel_organiz_49d2b6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
    ]
