# Generated by Django 4.2.7 on 2025-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0005_parcelle_latitude_parcelle_longitude_parcelle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='area_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='centroid_x',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='centroid_y',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='conseils',
            field=models.TextField(blank=True, verbose_name='Conseils'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Géométrie GeoJSON'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='maxx',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='maxy',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='minx',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='miny',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='perimeter_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
