# Generated by Django 4.2.7 on 2025-10-19 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_create_default_orgsettings'),
        ('referentiels', '0006_parcelle_area_m2_parcelle_centroid_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(upload_to='imports/quarantine/')),
                ('status', models.CharField(default='quarantine', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='cepages',
            field=models.ManyToManyField(blank=True, to='referentiels.cepage', verbose_name='Cépages'),
        ),
        migrations.CreateModel(
            name='ImportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undo_token', models.CharField(max_length=64, unique=True)),
                ('created_objects', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='referentiels.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_executions', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
