# Generated by Django 5.2.8 on 2025-11-30 17:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0007_importbatch_parcelle_cepages_importexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelleEncepagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Pourcentage (%)')),
                ('rang_debut', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang de début')),
                ('rang_fin', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang de fin')),
                ('annee_plantation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Année de plantation')),
                ('porte_greffe', models.CharField(blank=True, max_length=100, verbose_name='Porte-greffe')),
                ('densite_pieds_ha', models.PositiveIntegerField(blank=True, null=True, verbose_name='Densité (pieds/ha)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encepagements', to='referentiels.cepage', verbose_name='Cépage')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encepagements', to='referentiels.parcelle', verbose_name='Parcelle')),
            ],
            options={
                'verbose_name': 'Encépagement',
                'verbose_name_plural': 'Encépagements',
                'ordering': ['rang_debut', '-pourcentage'],
            },
        ),
    ]
