# Generated by Django 5.2.8 on 2025-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0008_add_parcelle_encepagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='zones_geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Zones de rangs'),
        ),
    ]
