# Generated by Django 5.2.8 on 2025-12-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0009_add_zones_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CepageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du cépage')),
                ('name_norm', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom normalisé')),
                ('synonymes', models.JSONField(blank=True, default=list, verbose_name='Synonymes')),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé'), ('gris', 'Gris')], default='rouge', max_length=10, verbose_name='Couleur')),
                ('regions', models.JSONField(blank=True, default=list, help_text='Liste des régions: bordeaux, bourgogne, alsace, champagne, loire, rhone, provence, languedoc, sud_ouest, jura, savoie, corse, beaujolais', verbose_name='Régions viticoles')),
                ('pays', models.CharField(default='France', max_length=50, verbose_name="Pays d'origine")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cépage (Référentiel)',
                'verbose_name_plural': 'Cépages (Référentiel)',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='cepage',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='referentiels.cepagereference', verbose_name='Cépage de référence'),
        ),
    ]
