# Generated by Django 5.2.8 on 2025-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cepages_reference'),
        ('referentiels', '0010_cepages_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cepage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cepage',
            constraint=models.UniqueConstraint(fields=('organization', 'name_norm'), name='unique_cepage_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='cepage',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('organization', 'code'), name='unique_cepage_code_per_org'),
        ),
    ]
