# Generated by Django 5.2.8 on 2025-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0011_fix_cepage_code_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cepage',
            name='couleur_libre',
            field=models.CharField(blank=True, help_text="Utilisé si couleur = 'Autre'", max_length=50, verbose_name='Couleur (saisie libre)'),
        ),
        migrations.AlterField(
            model_name='cepage',
            name='couleur',
            field=models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé'), ('gris', 'Gris'), ('autre', 'Autre')], default='rouge', max_length=20, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='cepagereference',
            name='couleur',
            field=models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('rose', 'Rosé'), ('gris', 'Gris'), ('autre', 'Autre')], default='rouge', max_length=10, verbose_name='Couleur'),
        ),
    ]
