# Generated by Django 5.0.14 on 2025-09-22 17:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_create_default_orgsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(help_text="Type d'entité: grape_variety, parcelle, unite, etc.", max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('file_path', models.CharField(help_text='Chemin stockage temporaire', max_length=500)),
                ('status', models.CharField(choices=[('uploaded', 'Fichier uploadé'), ('previewed', 'Aperçu généré'), ('mapped', 'Mapping configuré'), ('dry_run', 'Validation effectuée'), ('running', 'Import en cours'), ('done', 'Import terminé'), ('failed', 'Import échoué'), ('cancelled', 'Import annulé')], default='uploaded', max_length=20)),
                ('total_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_encoding', models.CharField(blank=True, max_length=50)),
                ('detected_delimiter', models.CharField(blank=True, max_length=5)),
                ('detected_decimal', models.CharField(blank=True, max_length=5)),
                ('has_header', models.BooleanField(default=True)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.JSONField(default=dict, help_text='Options spécifiques: sheet XLSX, etc.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='accounts.organization')),
            ],
            options={
                'db_table': 'import_job',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJobRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Numéro ligne dans fichier (1-based)')),
                ('status', models.CharField(choices=[('ok', 'Ligne valide'), ('warning', 'Avertissement'), ('error', 'Erreur bloquante')], max_length=10)),
                ('field', models.CharField(blank=True, help_text='Champ concerné', max_length=100)),
                ('message', models.TextField(help_text="Message d'erreur/warning")),
                ('suggestion', models.TextField(blank=True, help_text="Suggestion d'amélioration")),
                ('raw_data', models.JSONField(help_text='Données ligne originale')),
                ('processed_data', models.JSONField(blank=True, help_text='Après transformations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
            ],
            options={
                'db_table': 'import_job_row',
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_column', models.CharField(help_text='Nom colonne CSV', max_length=100)),
                ('csv_index', models.PositiveIntegerField(help_text='Index colonne (0-based)')),
                ('entity_field', models.CharField(help_text='Champ entité cible', max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique_key', models.BooleanField(default=False)),
                ('transforms', models.JSONField(default=list, help_text="Liste transformations: ['trim', 'unaccent']")),
                ('options', models.JSONField(default=dict, help_text='Options transformation')),
                ('confidence', models.FloatField(default=0.0, help_text='Confiance auto-mapping (0-1)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='imports.importjob')),
            ],
            options={
                'db_table': 'import_mapping',
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('name', models.CharField(help_text='Nom template', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mapping_config', models.JSONField(help_text='Configuration mapping complète')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to='accounts.organization')),
            ],
            options={
                'db_table': 'import_template',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['organization', 'entity', 'status'], name='import_job_organiz_c7b654_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['organization', 'created_by', '-started_at'], name='import_job_organiz_fd9f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', '-started_at'], name='import_job_status_70db71_idx'),
        ),
        migrations.AddIndex(
            model_name='importjobrow',
            index=models.Index(fields=['job', 'status'], name='import_job__job_id_ef2651_idx'),
        ),
        migrations.AddIndex(
            model_name='importjobrow',
            index=models.Index(fields=['job', 'row_index'], name='import_job__job_id_6fa75b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importjobrow',
            unique_together={('job', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='importmapping',
            index=models.Index(fields=['job', 'entity_field'], name='import_mapp_job_id_093630_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importmapping',
            unique_together={('job', 'csv_column'), ('job', 'entity_field')},
        ),
        migrations.AddIndex(
            model_name='importtemplate',
            index=models.Index(fields=['organization', 'entity'], name='import_temp_organiz_cb8afe_idx'),
        ),
        migrations.AddIndex(
            model_name='importtemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='import_temp_created_9bee65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importtemplate',
            unique_together={('organization', 'entity', 'name')},
        ),
    ]
